FROM python:3.14-slim
LABEL authors="ziomciopoziomcio"

RUN groupadd -r appservice && useradd -r -g appservice appservice

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY --chown=appservice:appservice . .

USER appservice
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]