# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x8d\x01\n\x11UserCreateRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\x0e\n\x06\x64\x65gree\x18\x05 \x01(\t\x12$\n\x1csend_login_credentials_email\x18\x06 \x01(\x08\"?\n\x12UserCreateResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2T\n\x0eUserRpcService\x12\x42\n\rCreateUserRPC\x12\x17.user.UserCreateRequest\x1a\x18.user.UserCreateResponseB\x1fZ\x1dgo_api/internal/rpc/user;userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035go_api/internal/rpc/user;user'
  _globals['_USERCREATEREQUEST']._serialized_start=21
  _globals['_USERCREATEREQUEST']._serialized_end=162
  _globals['_USERCREATERESPONSE']._serialized_start=164
  _globals['_USERCREATERESPONSE']._serialized_end=227
  _globals['_USERRPCSERVICE']._serialized_start=229
  _globals['_USERRPCSERVICE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
