package facilities_handlers

import (
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"

	"go_api/internal/app"
	"go_api/internal/models/facilities_models"
)

// GetRooms godoc
// @Summary Get rooms
// @Description Returns paginated list of rooms
// @Tags rooms
// @Produce json
// @Param limit query int false "Limit" default(10)
// @Param offset query int false "Offset" default(0)
// @Success 200 {object} facilities_models.PaginatedRoomsResponse
// @Failure 500 {object} map[string]string
// @Router /api/v1/rooms [get]
func GetRooms(app *app.App) gin.HandlerFunc {
	return func(c *gin.Context) {
		limitStr := c.DefaultQuery("limit", "10")
		offsetStr := c.DefaultQuery("offset", "0")

		limit, err := strconv.Atoi(limitStr)
		if err != nil || limit <= 0 {
			limit = 10
		}
		offset, err := strconv.Atoi(offsetStr)
		if err != nil || offset < 0 {
			offset = 0
		}

		rooms, total, err := app.Facilities.GetRooms(limit, offset)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}

		c.JSON(http.StatusOK, facilities_models.PaginatedRoomsResponse{
			Total:  total,
			Limit:  limit,
			Offset: offset,
			Items:  rooms,
		})
	}
}

// CreateRoom godoc
// @Summary Create room
// @Description Creates a new room. ID is generated by database and cannot be provided by client.
// @Tags rooms
// @Accept json
// @Produce json
// @Param request body facilities_models.Room true "Room data"
// @Success 201 {object} map[string]facilities_models.Room
// @Failure 400 {object} map[string]string
// @Failure 500 {object} map[string]string
// @Router /api/v1/rooms [post]
func CreateRoom(app *app.App) gin.HandlerFunc {
	return func(c *gin.Context) {
		var room facilities_models.Room

		if err := c.ShouldBindJSON(&room); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{
				"error": err.Error(),
			})
			return
		}

		if err := app.Facilities.CreateRoom(&room); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{
				"error": err.Error(),
			})
			return
		}

		c.JSON(http.StatusCreated, gin.H{
			"data": room,
		})
	}
}
