// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StudentProfile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StudyProgramId int32                  `protobuf:"varint,1,opt,name=study_program_id,json=studyProgramId,proto3" json:"study_program_id,omitempty"`
	MajorId        int32                  `protobuf:"varint,2,opt,name=major_id,json=majorId,proto3" json:"major_id,omitempty"`
	Id             int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StudentProfile) Reset() {
	*x = StudentProfile{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentProfile) ProtoMessage() {}

func (x *StudentProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentProfile.ProtoReflect.Descriptor instead.
func (*StudentProfile) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *StudentProfile) GetStudyProgramId() int32 {
	if x != nil {
		return x.StudyProgramId
	}
	return 0
}

func (x *StudentProfile) GetMajorId() int32 {
	if x != nil {
		return x.MajorId
	}
	return 0
}

func (x *StudentProfile) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmployeeProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FacultyId     int32                  `protobuf:"varint,1,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	UnitId        int32                  `protobuf:"varint,2,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeProfile) Reset() {
	*x = EmployeeProfile{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeProfile) ProtoMessage() {}

func (x *EmployeeProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeProfile.ProtoReflect.Descriptor instead.
func (*EmployeeProfile) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeeProfile) GetFacultyId() int32 {
	if x != nil {
		return x.FacultyId
	}
	return 0
}

func (x *EmployeeProfile) GetUnitId() int32 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *EmployeeProfile) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserCreateRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Email                     string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname                   string                 `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	PhoneNumber               string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Degree                    string                 `protobuf:"bytes,5,opt,name=degree,proto3" json:"degree,omitempty"`
	SendLoginCredentialsEmail bool                   `protobuf:"varint,6,opt,name=send_login_credentials_email,json=sendLoginCredentialsEmail,proto3" json:"send_login_credentials_email,omitempty"`
	// Types that are valid to be assigned to Profile:
	//
	//	*UserCreateRequest_Student
	//	*UserCreateRequest_Employee
	Profile       isUserCreateRequest_Profile `protobuf_oneof:"profile"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateRequest) Reset() {
	*x = UserCreateRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateRequest) ProtoMessage() {}

func (x *UserCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateRequest.ProtoReflect.Descriptor instead.
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserCreateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserCreateRequest) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *UserCreateRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserCreateRequest) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *UserCreateRequest) GetSendLoginCredentialsEmail() bool {
	if x != nil {
		return x.SendLoginCredentialsEmail
	}
	return false
}

func (x *UserCreateRequest) GetProfile() isUserCreateRequest_Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *UserCreateRequest) GetStudent() *StudentProfile {
	if x != nil {
		if x, ok := x.Profile.(*UserCreateRequest_Student); ok {
			return x.Student
		}
	}
	return nil
}

func (x *UserCreateRequest) GetEmployee() *EmployeeProfile {
	if x != nil {
		if x, ok := x.Profile.(*UserCreateRequest_Employee); ok {
			return x.Employee
		}
	}
	return nil
}

type isUserCreateRequest_Profile interface {
	isUserCreateRequest_Profile()
}

type UserCreateRequest_Student struct {
	Student *StudentProfile `protobuf:"bytes,7,opt,name=student,proto3,oneof"`
}

type UserCreateRequest_Employee struct {
	Employee *EmployeeProfile `protobuf:"bytes,8,opt,name=employee,proto3,oneof"`
}

func (*UserCreateRequest_Student) isUserCreateRequest_Profile() {}

func (*UserCreateRequest_Employee) isUserCreateRequest_Profile() {}

type UserCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateResponse) Reset() {
	*x = UserCreateResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateResponse) ProtoMessage() {}

func (x *UserCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateResponse.ProtoReflect.Descriptor instead.
func (*UserCreateResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserCreateResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserCreateResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserCreateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UserDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteRequest) Reset() {
	*x = UserDeleteRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteRequest) ProtoMessage() {}

func (x *UserDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteRequest.ProtoReflect.Descriptor instead.
func (*UserDeleteRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserDeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteResponse) Reset() {
	*x = UserDeleteResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteResponse) ProtoMessage() {}

func (x *UserDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteResponse.ProtoReflect.Descriptor instead.
func (*UserDeleteResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetRequest) Reset() {
	*x = UserGetRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetRequest) ProtoMessage() {}

func (x *UserGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetRequest.ProtoReflect.Descriptor instead.
func (*UserGetRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserGetRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserGetResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email       string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Surname     string                 `protobuf:"bytes,4,opt,name=surname,proto3" json:"surname,omitempty"`
	PhoneNumber string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Degree      string                 `protobuf:"bytes,6,opt,name=degree,proto3" json:"degree,omitempty"`
	// Types that are valid to be assigned to Profile:
	//
	//	*UserGetResponse_Student
	//	*UserGetResponse_Employee
	Profile       isUserGetResponse_Profile `protobuf_oneof:"profile"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetResponse) Reset() {
	*x = UserGetResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetResponse) ProtoMessage() {}

func (x *UserGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetResponse.ProtoReflect.Descriptor instead.
func (*UserGetResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserGetResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserGetResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserGetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserGetResponse) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *UserGetResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserGetResponse) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *UserGetResponse) GetProfile() isUserGetResponse_Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *UserGetResponse) GetStudent() *StudentProfile {
	if x != nil {
		if x, ok := x.Profile.(*UserGetResponse_Student); ok {
			return x.Student
		}
	}
	return nil
}

func (x *UserGetResponse) GetEmployee() *EmployeeProfile {
	if x != nil {
		if x, ok := x.Profile.(*UserGetResponse_Employee); ok {
			return x.Employee
		}
	}
	return nil
}

type isUserGetResponse_Profile interface {
	isUserGetResponse_Profile()
}

type UserGetResponse_Student struct {
	Student *StudentProfile `protobuf:"bytes,7,opt,name=student,proto3,oneof"`
}

type UserGetResponse_Employee struct {
	Employee *EmployeeProfile `protobuf:"bytes,8,opt,name=employee,proto3,oneof"`
}

func (*UserGetResponse_Student) isUserGetResponse_Profile() {}

func (*UserGetResponse_Employee) isUserGetResponse_Profile() {}

type SaveUserApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiKeyHash    string                 `protobuf:"bytes,2,opt,name=api_key_hash,json=apiKeyHash,proto3" json:"api_key_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserApiKeyRequest) Reset() {
	*x = SaveUserApiKeyRequest{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserApiKeyRequest) ProtoMessage() {}

func (x *SaveUserApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserApiKeyRequest.ProtoReflect.Descriptor instead.
func (*SaveUserApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *SaveUserApiKeyRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SaveUserApiKeyRequest) GetApiKeyHash() string {
	if x != nil {
		return x.ApiKeyHash
	}
	return ""
}

type SaveUserApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserApiKeyResponse) Reset() {
	*x = SaveUserApiKeyResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserApiKeyResponse) ProtoMessage() {}

func (x *SaveUserApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserApiKeyResponse.ProtoReflect.Descriptor instead.
func (*SaveUserApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *SaveUserApiKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AuthenticateApiKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProvidedApiKey string                 `protobuf:"bytes,1,opt,name=provided_api_key,json=providedApiKey,proto3" json:"provided_api_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthenticateApiKeyRequest) Reset() {
	*x = AuthenticateApiKeyRequest{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateApiKeyRequest) ProtoMessage() {}

func (x *AuthenticateApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateApiKeyRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *AuthenticateApiKeyRequest) GetProvidedApiKey() string {
	if x != nil {
		return x.ProvidedApiKey
	}
	return ""
}

type AuthenticateApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,2,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateApiKeyResponse) Reset() {
	*x = AuthenticateApiKeyResponse{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateApiKeyResponse) ProtoMessage() {}

func (x *AuthenticateApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateApiKeyResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *AuthenticateApiKeyResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthenticateApiKeyResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"e\n" +
	"\x0eStudentProfile\x12(\n" +
	"\x10study_program_id\x18\x01 \x01(\x05R\x0estudyProgramId\x12\x19\n" +
	"\bmajor_id\x18\x02 \x01(\x05R\amajorId\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\"Y\n" +
	"\x0fEmployeeProfile\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x01 \x01(\x05R\tfacultyId\x12\x17\n" +
	"\aunit_id\x18\x02 \x01(\x05R\x06unitId\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\"\xc5\x02\n" +
	"\x11UserCreateRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x03 \x01(\tR\asurname\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06degree\x18\x05 \x01(\tR\x06degree\x12?\n" +
	"\x1csend_login_credentials_email\x18\x06 \x01(\bR\x19sendLoginCredentialsEmail\x120\n" +
	"\astudent\x18\a \x01(\v2\x14.user.StudentProfileH\x00R\astudent\x123\n" +
	"\bemployee\x18\b \x01(\v2\x15.user.EmployeeProfileH\x00R\bemployeeB\t\n" +
	"\aprofile\"R\n" +
	"\x12UserCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"#\n" +
	"\x11UserDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"H\n" +
	"\x12UserDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\x0eUserGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x92\x02\n" +
	"\x0fUserGetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x04 \x01(\tR\asurname\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06degree\x18\x06 \x01(\tR\x06degree\x120\n" +
	"\astudent\x18\a \x01(\v2\x14.user.StudentProfileH\x00R\astudent\x123\n" +
	"\bemployee\x18\b \x01(\v2\x15.user.EmployeeProfileH\x00R\bemployeeB\t\n" +
	"\aprofile\"R\n" +
	"\x15SaveUserApiKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12 \n" +
	"\fapi_key_hash\x18\x02 \x01(\tR\n" +
	"apiKeyHash\"2\n" +
	"\x16SaveUserApiKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\x19AuthenticateApiKeyRequest\x12(\n" +
	"\x10provided_api_key\x18\x01 \x01(\tR\x0eprovidedApiKey\"P\n" +
	"\x1aAuthenticateApiKeyResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x19\n" +
	"\bis_admin\x18\x02 \x01(\bR\aisAdmin2\xff\x02\n" +
	"\x0eUserRpcService\x12B\n" +
	"\rCreateUserRPC\x12\x17.user.UserCreateRequest\x1a\x18.user.UserCreateResponse\x12B\n" +
	"\rDeleteUserRPC\x12\x17.user.UserDeleteRequest\x1a\x18.user.UserDeleteResponse\x129\n" +
	"\n" +
	"GetUserRPC\x12\x14.user.UserGetRequest\x1a\x15.user.UserGetResponse\x12N\n" +
	"\x11SaveUserApiKeyRPC\x12\x1b.user.SaveUserApiKeyRequest\x1a\x1c.user.SaveUserApiKeyResponse\x12Z\n" +
	"\x15AuthenticateApiKeyRPC\x12\x1f.user.AuthenticateApiKeyRequest\x1a .user.AuthenticateApiKeyResponseB\x1aZ\x18./internal/rpc/user;userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_user_proto_goTypes = []any{
	(*StudentProfile)(nil),             // 0: user.StudentProfile
	(*EmployeeProfile)(nil),            // 1: user.EmployeeProfile
	(*UserCreateRequest)(nil),          // 2: user.UserCreateRequest
	(*UserCreateResponse)(nil),         // 3: user.UserCreateResponse
	(*UserDeleteRequest)(nil),          // 4: user.UserDeleteRequest
	(*UserDeleteResponse)(nil),         // 5: user.UserDeleteResponse
	(*UserGetRequest)(nil),             // 6: user.UserGetRequest
	(*UserGetResponse)(nil),            // 7: user.UserGetResponse
	(*SaveUserApiKeyRequest)(nil),      // 8: user.SaveUserApiKeyRequest
	(*SaveUserApiKeyResponse)(nil),     // 9: user.SaveUserApiKeyResponse
	(*AuthenticateApiKeyRequest)(nil),  // 10: user.AuthenticateApiKeyRequest
	(*AuthenticateApiKeyResponse)(nil), // 11: user.AuthenticateApiKeyResponse
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: user.UserCreateRequest.student:type_name -> user.StudentProfile
	1,  // 1: user.UserCreateRequest.employee:type_name -> user.EmployeeProfile
	0,  // 2: user.UserGetResponse.student:type_name -> user.StudentProfile
	1,  // 3: user.UserGetResponse.employee:type_name -> user.EmployeeProfile
	2,  // 4: user.UserRpcService.CreateUserRPC:input_type -> user.UserCreateRequest
	4,  // 5: user.UserRpcService.DeleteUserRPC:input_type -> user.UserDeleteRequest
	6,  // 6: user.UserRpcService.GetUserRPC:input_type -> user.UserGetRequest
	8,  // 7: user.UserRpcService.SaveUserApiKeyRPC:input_type -> user.SaveUserApiKeyRequest
	10, // 8: user.UserRpcService.AuthenticateApiKeyRPC:input_type -> user.AuthenticateApiKeyRequest
	3,  // 9: user.UserRpcService.CreateUserRPC:output_type -> user.UserCreateResponse
	5,  // 10: user.UserRpcService.DeleteUserRPC:output_type -> user.UserDeleteResponse
	7,  // 11: user.UserRpcService.GetUserRPC:output_type -> user.UserGetResponse
	9,  // 12: user.UserRpcService.SaveUserApiKeyRPC:output_type -> user.SaveUserApiKeyResponse
	11, // 13: user.UserRpcService.AuthenticateApiKeyRPC:output_type -> user.AuthenticateApiKeyResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[2].OneofWrappers = []any{
		(*UserCreateRequest_Student)(nil),
		(*UserCreateRequest_Employee)(nil),
	}
	file_user_proto_msgTypes[7].OneofWrappers = []any{
		(*UserGetResponse_Student)(nil),
		(*UserGetResponse_Employee)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
