// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserRpcService_CreateUserRPC_FullMethodName         = "/user.UserRpcService/CreateUserRPC"
	UserRpcService_DeleteUserRPC_FullMethodName         = "/user.UserRpcService/DeleteUserRPC"
	UserRpcService_GetUserRPC_FullMethodName            = "/user.UserRpcService/GetUserRPC"
	UserRpcService_SaveUserApiKeyRPC_FullMethodName     = "/user.UserRpcService/SaveUserApiKeyRPC"
	UserRpcService_AuthenticateApiKeyRPC_FullMethodName = "/user.UserRpcService/AuthenticateApiKeyRPC"
)

// UserRpcServiceClient is the client API for UserRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRpcServiceClient interface {
	CreateUserRPC(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error)
	DeleteUserRPC(ctx context.Context, in *UserDeleteRequest, opts ...grpc.CallOption) (*UserDeleteResponse, error)
	GetUserRPC(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error)
	SaveUserApiKeyRPC(ctx context.Context, in *SaveUserApiKeyRequest, opts ...grpc.CallOption) (*SaveUserApiKeyResponse, error)
	AuthenticateApiKeyRPC(ctx context.Context, in *AuthenticateApiKeyRequest, opts ...grpc.CallOption) (*AuthenticateApiKeyResponse, error)
}

type userRpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRpcServiceClient(cc grpc.ClientConnInterface) UserRpcServiceClient {
	return &userRpcServiceClient{cc}
}

func (c *userRpcServiceClient) CreateUserRPC(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCreateResponse)
	err := c.cc.Invoke(ctx, UserRpcService_CreateUserRPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcServiceClient) DeleteUserRPC(ctx context.Context, in *UserDeleteRequest, opts ...grpc.CallOption) (*UserDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDeleteResponse)
	err := c.cc.Invoke(ctx, UserRpcService_DeleteUserRPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcServiceClient) GetUserRPC(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetResponse)
	err := c.cc.Invoke(ctx, UserRpcService_GetUserRPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcServiceClient) SaveUserApiKeyRPC(ctx context.Context, in *SaveUserApiKeyRequest, opts ...grpc.CallOption) (*SaveUserApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveUserApiKeyResponse)
	err := c.cc.Invoke(ctx, UserRpcService_SaveUserApiKeyRPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcServiceClient) AuthenticateApiKeyRPC(ctx context.Context, in *AuthenticateApiKeyRequest, opts ...grpc.CallOption) (*AuthenticateApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateApiKeyResponse)
	err := c.cc.Invoke(ctx, UserRpcService_AuthenticateApiKeyRPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRpcServiceServer is the server API for UserRpcService service.
// All implementations must embed UnimplementedUserRpcServiceServer
// for forward compatibility.
type UserRpcServiceServer interface {
	CreateUserRPC(context.Context, *UserCreateRequest) (*UserCreateResponse, error)
	DeleteUserRPC(context.Context, *UserDeleteRequest) (*UserDeleteResponse, error)
	GetUserRPC(context.Context, *UserGetRequest) (*UserGetResponse, error)
	SaveUserApiKeyRPC(context.Context, *SaveUserApiKeyRequest) (*SaveUserApiKeyResponse, error)
	AuthenticateApiKeyRPC(context.Context, *AuthenticateApiKeyRequest) (*AuthenticateApiKeyResponse, error)
	mustEmbedUnimplementedUserRpcServiceServer()
}

// UnimplementedUserRpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserRpcServiceServer struct{}

func (UnimplementedUserRpcServiceServer) CreateUserRPC(context.Context, *UserCreateRequest) (*UserCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserRPC not implemented")
}
func (UnimplementedUserRpcServiceServer) DeleteUserRPC(context.Context, *UserDeleteRequest) (*UserDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserRPC not implemented")
}
func (UnimplementedUserRpcServiceServer) GetUserRPC(context.Context, *UserGetRequest) (*UserGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRPC not implemented")
}
func (UnimplementedUserRpcServiceServer) SaveUserApiKeyRPC(context.Context, *SaveUserApiKeyRequest) (*SaveUserApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveUserApiKeyRPC not implemented")
}
func (UnimplementedUserRpcServiceServer) AuthenticateApiKeyRPC(context.Context, *AuthenticateApiKeyRequest) (*AuthenticateApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthenticateApiKeyRPC not implemented")
}
func (UnimplementedUserRpcServiceServer) mustEmbedUnimplementedUserRpcServiceServer() {}
func (UnimplementedUserRpcServiceServer) testEmbeddedByValue()                        {}

// UnsafeUserRpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRpcServiceServer will
// result in compilation errors.
type UnsafeUserRpcServiceServer interface {
	mustEmbedUnimplementedUserRpcServiceServer()
}

func RegisterUserRpcServiceServer(s grpc.ServiceRegistrar, srv UserRpcServiceServer) {
	// If the following call panics, it indicates UnimplementedUserRpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserRpcService_ServiceDesc, srv)
}

func _UserRpcService_CreateUserRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServiceServer).CreateUserRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpcService_CreateUserRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServiceServer).CreateUserRPC(ctx, req.(*UserCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpcService_DeleteUserRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServiceServer).DeleteUserRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpcService_DeleteUserRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServiceServer).DeleteUserRPC(ctx, req.(*UserDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpcService_GetUserRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServiceServer).GetUserRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpcService_GetUserRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServiceServer).GetUserRPC(ctx, req.(*UserGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpcService_SaveUserApiKeyRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUserApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServiceServer).SaveUserApiKeyRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpcService_SaveUserApiKeyRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServiceServer).SaveUserApiKeyRPC(ctx, req.(*SaveUserApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpcService_AuthenticateApiKeyRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServiceServer).AuthenticateApiKeyRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpcService_AuthenticateApiKeyRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServiceServer).AuthenticateApiKeyRPC(ctx, req.(*AuthenticateApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRpcService_ServiceDesc is the grpc.ServiceDesc for UserRpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserRpcService",
	HandlerType: (*UserRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserRPC",
			Handler:    _UserRpcService_CreateUserRPC_Handler,
		},
		{
			MethodName: "DeleteUserRPC",
			Handler:    _UserRpcService_DeleteUserRPC_Handler,
		},
		{
			MethodName: "GetUserRPC",
			Handler:    _UserRpcService_GetUserRPC_Handler,
		},
		{
			MethodName: "SaveUserApiKeyRPC",
			Handler:    _UserRpcService_SaveUserApiKeyRPC_Handler,
		},
		{
			MethodName: "AuthenticateApiKeyRPC",
			Handler:    _UserRpcService_AuthenticateApiKeyRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
