from typing import Callable

from sqlalchemy.orm import Session

from src.academics.models import Employees, Units
from src.users.models import Users, Roles
from src.facilities.models import Faculty


def _get_admin_role_obj(roles: dict[str, Roles]) -> Roles:
    admin_obj = roles.get("Administrator", None)
    if admin_obj is None:
        raise Exception("No Administrator role found")
    return admin_obj


def create_user_admin(
    session: Session,
    password_hash_func: Callable[[str], str] | None,
    roles: dict[str, Roles],
    db_faculties: dict[str, Faculty],
    db_units: dict[str, Units],
):
    """
    Create an admin user
    :param session: database session
    :param password_hash_func: hash function for passwords
        (in case of None, hash is the same as plain password)
    :param roles: dictionary mapping role names to Roles objects
        (generated by generate_roles_from_excel_file)
    :param db_faculties: dictionary mapping faculty short name to Faculty
    :param db_units: dictionary mapping unit short name to Units
    :return: Admin User object and Employee object
    """
    if password_hash_func is None:

        def not_a_hash(text: str) -> str:
            return text

        password_hash_func = not_a_hash

    mail = "admin@nimda.pl"
    password = "qwerty"
    password_hash = password_hash_func(password)
    name = "Admin"
    surname = "Adminkowski"
    admin_role_obj = _get_admin_role_obj(roles)

    user_obj = Users(
        password_hash=password_hash,
        email=mail,
        phone_number="123456789",
        name=name,
        surname=surname,
        degree=None,
        roles=[admin_role_obj],
        email_verified=True,
    )
    session.add(user_obj)
    session.flush()

    unit_obj = db_units["I24"]
    unit_id = unit_obj.id

    fac_obj = db_faculties["WEEIA"]
    fac_id = fac_obj.id

    emp_obj = Employees(
        user_id=user_obj.id,
        faculty_id=fac_id,
        unit_id=unit_id,
    )
    session.add(emp_obj)
    session.flush()

    return user_obj, emp_obj
