"""add force_password_change to users

Revision ID: 2f2ebb990b36
Revises: fb4384713a41
Create Date: 2026-04-29 18:44:52.116141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2ebb990b36'
down_revision: Union[str, Sequence[str], None] = 'fb4384713a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'semester',
               existing_type=sa.INTEGER(),
               server_default='1',
               existing_nullable=False)
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'force_password_change')
    op.alter_column('groups', 'semester',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
