"""Added academics calendar

Revision ID: 37622c66ff7f
Revises: fe692366c6b4
Create Date: 2026-03-22 00:41:06.611236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37622c66ff7f'
down_revision: Union[str, Sequence[str], None] = 'fe692366c6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_calendar',
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester_type', sa.Enum('WINTER', 'SUMMER', name='semestertype'), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('academic_day_of_week', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.CheckConstraint('academic_day_of_week >= 1 AND academic_day_of_week <= 7', name='chk_academic_calendar_day_of_week'),
    sa.CheckConstraint('week_number >= 1 AND week_number <= 20', name='chk_academic_calendar_week_number'),
    sa.PrimaryKeyConstraint('calendar_date'),
    sa.UniqueConstraint('academic_year', 'semester_type', 'week_number', 'academic_day_of_week', name='uq_academic_calendar_week_day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('academic_calendar')
    # ### end Alembic commands ###
