"""init_database

Revision ID: 3a60c50449d0
Revises: 
Create Date: 2026-03-07 19:02:00.069981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a60c50449d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campus_name', sa.String(length=255), nullable=True),
    sa.Column('campus_short', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_name'),
    sa.UniqueConstraint('campus_short')
    )
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('faculty_name', sa.String(length=255), nullable=False),
    sa.Column('faculty_short', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_name'),
    sa.UniqueConstraint('faculty_short')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_name', sa.String(length=255), nullable=True),
    sa.Column('building_number', sa.String(length=255), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_number')
    )
    op.create_table('study_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('faculty', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['faculty'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_name')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_name', sa.String(length=255), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('unit_short', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_name'),
    sa.UniqueConstraint('unit_short')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('elective_block',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_field', sa.Integer(), nullable=False),
    sa.Column('block_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['study_field'], ['study_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('workload', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'unit_id', 'faculty_id', name='uq_employees_user_id')
    )
    op.create_table('faculty_buildings',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('faculty_id', 'building_id')
    )
    op.create_table('major',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_field', sa.Integer(), nullable=True),
    sa.Column('major_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['study_field'], ['study_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_name', sa.String(length=255), nullable=False),
    sa.Column('projector_availability', sa.Boolean(), nullable=False),
    sa.Column('pc_amount', sa.Integer(), nullable=False),
    sa.Column('room_capacity', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_name', 'building_id', name='uq_room_building')
    )
    op.create_table('courses',
    sa.Column('course_code', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ects_points', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('course_language', sa.Enum('POLISH', 'ENGLISH', 'FRENCH', name='courselanguage'), nullable=False),
    sa.Column('leading_unit', sa.Integer(), nullable=False),
    sa.Column('course_coordinator', sa.Integer(), nullable=False),
    sa.Column('study_field', sa.Integer(), nullable=False),
    sa.Column('major', sa.Integer(), nullable=True),
    sa.Column('elective_block', sa.Integer(), nullable=True),
    sa.CheckConstraint('(major IS NULL) OR (elective_block IS NULL)', name='chk_courses_major_elective'),
    sa.ForeignKeyConstraint(['course_coordinator'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['elective_block'], ['elective_block.id'], ),
    sa.ForeignKeyConstraint(['leading_unit'], ['units.id'], ),
    sa.ForeignKeyConstraint(['major'], ['major.id'], ),
    sa.ForeignKeyConstraint(['study_field'], ['study_fields.id'], ),
    sa.PrimaryKeyConstraint('course_code')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('study_field', sa.Integer(), nullable=False),
    sa.Column('major', sa.Integer(), nullable=True),
    sa.Column('elective_block', sa.Integer(), nullable=True),
    sa.CheckConstraint('(major IS NULL) OR (elective_block IS NULL)', name='check_major_elective_block'),
    sa.ForeignKeyConstraint(['elective_block'], ['elective_block.id'], ),
    sa.ForeignKeyConstraint(['major'], ['major.id'], ),
    sa.ForeignKeyConstraint(['study_field'], ['study_fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('study_field', sa.Integer(), nullable=False),
    sa.Column('major', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['major'], ['major.id'], ),
    sa.ForeignKeyConstraint(['study_field'], ['study_fields.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'study_field', name='uq_students_user_id')
    )
    op.create_table('course_type_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('class_type', sa.Enum('LECTURE', 'TUTORIALS', 'LABORATORY', 'SEMINAR', 'OTHER', 'ELEARNING', name='classtype'), nullable=False),
    sa.Column('class_hours', sa.Integer(), nullable=False),
    sa.Column('pc_needed', sa.Boolean(), nullable=False),
    sa.Column('projector_needed', sa.Boolean(), nullable=False),
    sa.Column('max_group_participants_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course'], ['courses.course_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course', 'class_type', name='uq_course_class_type')
    )
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('student', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['student'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group', 'student', name='uq_group_members_group_id')
    )
    op.create_table('courses_instructors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee', sa.Integer(), nullable=False),
    sa.Column('course_type_details', sa.Integer(), nullable=False),
    sa.Column('min_hours', sa.Integer(), nullable=True),
    sa.Column('max_hours', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_type_details'], ['course_type_details.id'], ),
    sa.ForeignKeyConstraint(['employee'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_type_details', 'employee', name='uq_course_type_details_employee')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses_instructors')
    op.drop_table('group_members')
    op.drop_table('course_type_details')
    op.drop_table('students')
    op.drop_table('groups')
    op.drop_table('courses')
    op.drop_table('rooms')
    op.drop_table('major')
    op.drop_table('faculty_buildings')
    op.drop_table('employees')
    op.drop_table('elective_block')
    op.drop_table('user_roles')
    op.drop_table('units')
    op.drop_table('study_fields')
    op.drop_table('buildings')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('faculty')
    op.drop_table('campus')
    # ### end Alembic commands ###
