"""Added semester to groups

Revision ID: 40faaaf1b6b1
Revises: bc968dc0a8ee
Create Date: 2026-04-23 11:53:35.098670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40faaaf1b6b1'
down_revision: Union[str, Sequence[str], None] = 'bc968dc0a8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('semester', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'semester')
    # ### end Alembic commands ###
