"""Added missing study field info

Revision ID: 4ab20155b177
Revises: bc968dc0a8ee
Create Date: 2026-04-22 11:49:08.479421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4ab20155b177"
down_revision: Union[str, Sequence[str], None] = "bc968dc0a8ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    studymode = sa.Enum("FULL_TIME", "PART_TIME", name="studymode")
    courselanguage = sa.Enum("POLISH", "ENGLISH", "FRENCH", name="courselanguage")

    studymode.create(op.get_bind(), checkfirst=True)
    courselanguage.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "study_fields",
        sa.Column(
            "language",
            sa.Enum("POLISH", "ENGLISH", "FRENCH", name="courselanguage"),
            nullable=False,
        ),
    )
    op.add_column(
        "study_fields",
        sa.Column(
            "mode", sa.Enum("FULL_TIME", "PART_TIME", name="studymode"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("study_fields", "mode")
    op.drop_column("study_fields", "language")
    # ### end Alembic commands ###
