"""Add planner settings

Revision ID: 61a8d28bddcb
Revises: d37f1916d724
Create Date: 2026-05-11 17:23:15.830172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "61a8d28bddcb"
down_revision: Union[str, Sequence[str], None] = "d37f1916d724"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "planner_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("faculty_id", sa.Integer(), nullable=False),
        sa.Column("planned_academic_year", sa.String(length=20), nullable=False),
        sa.Column(
            "planned_semester_type",
            sa.Enum("WINTER", "SUMMER", name="semestertype", create_type=False),
            nullable=False,
        ),
        sa.Column("is_planning_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["faculty_id"],
            ["faculties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("faculty_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("planner_settings")
    # ### end Alembic commands ###
