"""Added study cycles

Revision ID: 839eac589551
Revises: 2f2ebb990b36
Create Date: 2026-05-10 22:06:07.113722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "839eac589551"
down_revision: Union[str, Sequence[str], None] = "2f2ebb990b36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    studydegree_enum = postgresql.ENUM(
        "BACHELOR", "MASTER", "UNIFORM_MASTER", "DOCTORAL", name="studydegree"
    )
    studydegree_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "study_fields",
        sa.Column(
            "degree", studydegree_enum, nullable=False, server_default="BACHELOR"
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("study_fields", "degree")
    # ### end Alembic commands ###
