"""table name correction

Revision ID: 984a3baf6269
Revises: 21214e084f6d
Create Date: 2026-03-16 20:42:39.940931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "984a3baf6269"
down_revision: Union[str, Sequence[str], None] = "21214e084f6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("course_code", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ects_points", sa.Integer(), nullable=False),
        sa.Column("course_name", sa.String(length=255), nullable=False),
        sa.Column(
            "course_language",
            postgresql.ENUM(
                "POLISH", "ENGLISH", "FRENCH", name="courselanguage", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("leading_unit", sa.Integer(), nullable=False),
        sa.Column("course_coordinator", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_coordinator"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["leading_unit"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("course_code"),
    ),
    op.drop_constraint(
        op.f("course_type_detail_course_fkey"), "course_type_detail", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "course_type_detail", "courses", ["course"], ["course_code"]
    )
    op.drop_constraint(
        op.f("curriculum_courses_course_fkey"), "curriculum_courses", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "curriculum_courses", "courses", ["course"], ["course_code"]
    )
    op.drop_table("course")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "curriculum_courses", type_="foreignkey")
    op.create_foreign_key(
        op.f("curriculum_courses_course_fkey"),
        "curriculum_courses",
        "course",
        ["course"],
        ["course_code"],
    )
    op.drop_constraint(None, "course_type_detail", type_="foreignkey")
    op.create_foreign_key(
        op.f("course_type_detail_course_fkey"),
        "course_type_detail",
        "course",
        ["course"],
        ["course_code"],
    )
    op.create_table(
        "course",
        sa.Column("course_code", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("ects_points", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "course_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "course_language",
            postgresql.ENUM(
                "POLISH",
                "ENGLISH",
                "FRENCH",
                name="courselanguage",
                create_type=False,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("leading_unit", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "course_coordinator", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["course_coordinator"],
            ["employees.id"],
            name=op.f("course_course_coordinator_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["leading_unit"], ["units.id"], name=op.f("course_leading_unit_fkey")
        ),
        sa.PrimaryKeyConstraint("course_code", name=op.f("course_pkey")),
    )
    op.drop_table("courses")
    # ### end Alembic commands ###
