"""studies program added-fix

Revision ID: 9f599bfdae65
Revises: 4e1659a2e927
Create Date: 2026-03-15 20:37:55.449785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f599bfdae65'
down_revision: Union[str, Sequence[str], None] = '4e1659a2e927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_field', sa.Integer(), nullable=False),
    sa.Column('start_year', sa.String(length=20), nullable=False),
    sa.Column('program_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['study_field'], ['study_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_program', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('major', sa.Integer(), nullable=True),
    sa.Column('elective_block', sa.Integer(), nullable=True),
    sa.CheckConstraint('(major IS NULL) OR (elective_block IS NULL)', name='chk_curriculum_major_elective'),
    sa.ForeignKeyConstraint(['course'], ['courses.course_code'], ),
    sa.ForeignKeyConstraint(['elective_block'], ['elective_block.id'], ),
    sa.ForeignKeyConstraint(['major'], ['major.id'], ),
    sa.ForeignKeyConstraint(['study_program'], ['study_programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_program', 'course', 'semester', name='uq_program_course_semester')
    )
    op.drop_constraint(op.f('courses_major_fkey'), 'courses', type_='foreignkey')
    op.drop_constraint(op.f('courses_study_field_fkey'), 'courses', type_='foreignkey')
    op.drop_constraint(op.f('courses_elective_block_fkey'), 'courses', type_='foreignkey')
    op.drop_column('courses', 'major')
    op.drop_column('courses', 'elective_block')
    op.drop_column('courses', 'study_field')
    op.add_column('groups', sa.Column('study_program', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('groups_study_field_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'study_programs', ['study_program'], ['id'])
    op.drop_column('groups', 'study_field')
    op.add_column('students', sa.Column('study_program', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_students_user_id'), 'students', type_='unique')
    op.create_unique_constraint('uq_students_user_id', 'students', ['user_id', 'study_program'])
    op.drop_constraint(op.f('students_study_field_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'study_programs', ['study_program'], ['id'])
    op.drop_column('students', 'study_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('study_field', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_study_field_fkey'), 'students', 'study_fields', ['study_field'], ['id'])
    op.drop_constraint('uq_students_user_id', 'students', type_='unique')
    op.create_unique_constraint(op.f('uq_students_user_id'), 'students', ['user_id', 'study_field'], postgresql_nulls_not_distinct=False)
    op.drop_column('students', 'study_program')
    op.add_column('groups', sa.Column('study_field', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_study_field_fkey'), 'groups', 'study_fields', ['study_field'], ['id'])
    op.drop_column('groups', 'study_program')
    op.add_column('courses', sa.Column('study_field', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('elective_block', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('major', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('courses_elective_block_fkey'), 'courses', 'elective_block', ['elective_block'], ['id'])
    op.create_foreign_key(op.f('courses_study_field_fkey'), 'courses', 'study_fields', ['study_field'], ['id'])
    op.create_foreign_key(op.f('courses_major_fkey'), 'courses', 'major', ['major'], ['id'])
    op.drop_table('curriculum_courses')
    op.drop_table('study_programs')
    # ### end Alembic commands ###
