"""Some schedule suggestions store fixes

Revision ID: a27c0606ed3e
Revises: c046ddc6b80f
Create Date: 2026-03-22 19:19:28.692935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27c0606ed3e'
down_revision: Union[str, Sequence[str], None] = 'c046ddc6b80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('target_class_session_id', sa.Uuid(), nullable=False),
    sa.Column('state_before', sa.JSON(), nullable=False),
    sa.Column('state_after', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'FAILED', name='suggestionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_suggestions_target_class_session_id'), 'schedule_suggestions', ['target_class_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_suggestions_target_class_session_id'), table_name='schedule_suggestions')
    op.drop_table('schedule_suggestions')
    # ### end Alembic commands ###
