"""primary keys instead of ids

Revision ID: a931ba7e5607
Revises: c58f1742aefa
Create Date: 2026-03-18 21:10:40.121548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a931ba7e5607"
down_revision: Union[str, Sequence[str], None] = "c58f1742aefa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TABLE course_type_detail DROP COLUMN IF EXISTS id CASCADE")
    op.execute("ALTER TABLE courses_instructors DROP COLUMN IF EXISTS id CASCADE")
    op.execute(
        "ALTER TABLE courses_instructors DROP COLUMN IF EXISTS course_type_detail CASCADE"
    )
    op.add_column(
        "courses_instructors", sa.Column("course", sa.Integer(), nullable=False)
    )
    op.add_column(
        "courses_instructors",
        sa.Column(
            "class_type",
            sa.Enum(
                "LECTURE",
                "TUTORIALS",
                "LABORATORY",
                "SEMINAR",
                "OTHER",
                "ELEARNING",
                name="classtype",
            ),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "fk_courses_instructors_course_type_detail",
        "courses_instructors",
        "course_type_detail",
        ["course", "class_type"],
        ["course", "class_type"],
    )
    op.execute("ALTER TABLE curriculum_courses DROP COLUMN IF EXISTS id CASCADE")
    op.execute("ALTER TABLE group_members DROP COLUMN IF EXISTS id CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group_members",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.create_unique_constraint(
        "uq_group_members_group_id", "group_members", ["group", "student"]
    )
    op.add_column(
        "curriculum_courses",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.create_unique_constraint(
        "uq_program_course_semester",
        "curriculum_courses",
        ["study_program", "course", "semester"],
    )
    op.add_column(
        "courses_instructors",
        sa.Column(
            "course_type_detail", sa.Integer(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "courses_instructors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    )
    op.drop_constraint(
        "fk_courses_instructors_course_type_detail",
        "courses_instructors",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "courses_instructors_course_type_detail_fkey",
        "courses_instructors",
        "course_type_detail",
        ["course_type_detail"],
        ["id"],
    )
    op.create_unique_constraint(
        "uq_course_type_details_employee",
        "courses_instructors",
        ["course_type_detail", "employee"],
    )
    op.drop_column("courses_instructors", "class_type")
    op.drop_column("courses_instructors", "course")
    op.add_column(
        "course_type_detail",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    )
    op.create_unique_constraint(
        "uq_course_class_type", "course_type_detail", ["course", "class_type"]
    )
    # ### end Alembic commands ###
