"""Added slots_per_class field

Revision ID: bc968dc0a8ee
Revises: e3b1a1775053
Create Date: 2026-03-26 21:30:52.447260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc968dc0a8ee'
down_revision: Union[str, Sequence[str], None] = 'e3b1a1775053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_suggestion_target_class_session_id'), table_name='schedule_suggestion')
    op.drop_table('schedule_suggestion')
    op.add_column('course_type_detail', sa.Column('slots_per_class', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_type_detail', 'slots_per_class')
    op.create_table('schedule_suggestion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('target_class_session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('state_before', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('state_after', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'FAILED', name='suggestionstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('schedule_suggestion_pkey'))
    )
    op.create_index(op.f('ix_schedule_suggestion_target_class_session_id'), 'schedule_suggestion', ['target_class_session_id'], unique=False)
    # ### end Alembic commands ###
