"""Added missing constraint

Revision ID: c58f1742aefa
Revises: 984a3baf6269
Create Date: 2026-03-16 21:34:51.584526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c58f1742aefa'
down_revision: Union[str, Sequence[str], None] = '984a3baf6269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_program_course_semester', 'curriculum_courses', ['study_program', 'course', 'semester'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_program_course_semester', 'curriculum_courses', type_='unique')
    # ### end Alembic commands ###
