"""Added settings

Revision ID: d37f1916d724
Revises: 839eac589551
Create Date: 2026-05-11 11:32:06.483949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd37f1916d724'
down_revision: Union[str, Sequence[str], None] = '839eac589551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_fields', 'degree',
               existing_type=postgresql.ENUM('BACHELOR', 'MASTER', 'UNIFORM_MASTER', 'DOCTORAL', name='studydegree'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_fields', 'degree',
               existing_type=postgresql.ENUM('BACHELOR', 'MASTER', 'UNIFORM_MASTER', 'DOCTORAL', name='studydegree'),
               server_default=sa.text("'BACHELOR'::studydegree"),
               existing_nullable=False)
    # ### end Alembic commands ###
