"""init_user_api_key

Revision ID: d51a6e0e50e5
Revises: 0e34a8750156
Create Date: 2026-06-07 12:58:34.518072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51a6e0e50e5'
down_revision: Union[str, Sequence[str], None] = '0e34a8750156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_api_keys_api_key_hash'), 'user_api_keys', ['api_key_hash'], unique=True)
    op.drop_index(op.f('ix_users_api_key_hash'), table_name='users')
    op.drop_column('users', 'api_key_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_api_key_hash'), 'users', ['api_key_hash'], unique=True)
    op.drop_index(op.f('ix_user_api_keys_api_key_hash'), table_name='user_api_keys')
    op.drop_table('user_api_keys')
    # ### end Alembic commands ###
