"""Change grade to degree in Users and delete workload in Employees

Revision ID: d6b412ffc363
Revises: f659a2697df6
Create Date: 2026-03-12 17:31:32.433441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b412ffc363'
down_revision: Union[str, Sequence[str], None] = 'f659a2697df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'workload')
    op.add_column('users', sa.Column('degree', sa.String(length=255), nullable=True))
    op.drop_column('users', 'grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('grade', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'degree')
    op.add_column('employees', sa.Column('workload', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
