"""Added schedule suggestions

Revision ID: d95cacf97cc2
Revises: fe692366c6b4
Create Date: 2026-03-22 17:12:19.926402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95cacf97cc2'
down_revision: Union[str, Sequence[str], None] = 'fe692366c6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_suggestion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('target_class_session_id', sa.Uuid(), nullable=False),
    sa.Column('state_before', sa.JSON(), nullable=False),
    sa.Column('state_after', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'FAILED', name='suggestionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_suggestion_target_class_session_id'), 'schedule_suggestion', ['target_class_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_suggestion_target_class_session_id'), table_name='schedule_suggestion')
    op.drop_table('schedule_suggestion')
    # ### end Alembic commands ###
