"""Added conversations details storing

Revision ID: e1382b633421
Revises: f7443cd86f66
Create Date: 2026-03-21 20:41:01.044480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1382b633421'
down_revision: Union[str, Sequence[str], None] = 'f7443cd86f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM', 'USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('uq_program_course_semester'), 'curriculum_courses', type_='unique')
    op.drop_constraint(op.f('uq_group_members_group_id'), 'group_members', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_group_members_group_id'), 'group_members', ['group', 'student'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_program_course_semester'), 'curriculum_courses', ['study_program', 'course', 'semester'], postgresql_nulls_not_distinct=False)
    op.drop_table('messages')
    op.drop_table('chats')
    # ### end Alembic commands ###
