"""Added frequency field to course_type_detail

Revision ID: e3b1a1775053
Revises: c4264966d1d9
Create Date: 2026-03-26 21:01:41.516689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e3b1a1775053"
down_revision: Union[str, Sequence[str], None] = "c4264966d1d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    frequency_type = sa.Enum(
        "EVERY_WEEK",
        "BIWEEKLY",
        "FIRST_HALF",
        "SECOND_HALF",
        "MANUAL",
        name="frequencytype",
    )
    frequency_type.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "course_type_detail",
        sa.Column(
            "frequency",
            sa.Enum(
                "EVERY_WEEK",
                "BIWEEKLY",
                "FIRST_HALF",
                "SECOND_HALF",
                "MANUAL",
                name="frequencytype",
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "course_type_detail", sa.Column("manual_weeks", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course_type_detail", "manual_weeks")
    op.drop_column("course_type_detail", "frequency")
    frequency_type = sa.Enum(name="frequencytype")
    frequency_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
