"""init_database

Revision ID: e41bb9ca2ca8
Revises: 3a60c50449d0
Create Date: 2026-03-07 22:51:39.801355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41bb9ca2ca8'
down_revision: Union[str, Sequence[str], None] = '3a60c50449d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elective_block', sa.Column('elective_block_name', sa.String(length=255), nullable=False))
    op.drop_column('elective_block', 'block_name')
    op.alter_column('rooms', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('elective_block', sa.Column('block_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('elective_block', 'elective_block_name')
    # ### end Alembic commands ###
