"""study field unique constraint

Revision ID: ec0cb16cddbd
Revises: d37f1916d724
Create Date: 2026-05-12 11:26:24.035320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0cb16cddbd'
down_revision: Union[str, Sequence[str], None] = 'd37f1916d724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('study_fields_field_name_key'), 'study_fields', type_='unique')
    op.create_unique_constraint('uq_field_name_degree', 'study_fields', ['field_name', 'degree'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_field_name_degree', 'study_fields', type_='unique')
    op.create_unique_constraint(op.f('study_fields_field_name_key'), 'study_fields', ['field_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
