"""api_keys_management

Revision ID: fa0c1a493f77
Revises: b71824338984
Create Date: 2026-06-15 10:58:20.659635

"""

from typing import Sequence, Union
from sqlalchemy.engine.reflection import Inspector

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fa0c1a493f77"
down_revision: Union[str, Sequence[str], None] = "b71824338984"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    existing_columns = [col["name"] for col in inspector.get_columns("user_api_keys")]

    if "expiration_date" not in existing_columns:
        op.add_column(
            "user_api_keys",
            sa.Column("expiration_date", sa.DateTime(timezone=True), nullable=True),
        )

    if "name" not in existing_columns:
        op.add_column(
            "user_api_keys",
            sa.Column(
                "name",
                sa.String(length=255),
                nullable=False,
                server_default="Default Key",
            ),
        )

    if "is_active" not in existing_columns:
        op.add_column(
            "user_api_keys",
            sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        )

    conn.execute(
        sa.text(
            "UPDATE user_api_keys SET expiration_date = NOW() + INTERVAL '365 days' WHERE expiration_date IS NULL"
        )
    )

    op.alter_column("user_api_keys", "expiration_date", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_api_keys",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "user_api_keys",
        "name",
        existing_type=sa.String(length=255),
        server_default=sa.text("'Default Key'::character varying"),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("user_api_keys", "expiration_date")
    # ### end Alembic commands ###
