"""primary_keys_instead_of_ids

Revision ID: fb600057d27c
Revises: 12a9e2c3e56e
Create Date: 2026-03-19 16:56:19.789438

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fb600057d27c"
down_revision: Union[str, Sequence[str], None] = "12a9e2c3e56e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "courses_instructors_course_type_detail_fkey",
        "courses_instructors",
        type_="foreignkey",
    )

    op.drop_constraint(
        op.f("uq_course_class_type"), "course_type_detail", type_="unique"
    )
    op.drop_column("course_type_detail", "id")

    op.create_primary_key(
        "pk_course_type_detail", "course_type_detail", ["course", "class_type"]
    )

    op.add_column(
        "courses_instructors", sa.Column("course", sa.Integer(), nullable=False)
    )
    op.add_column(
        "courses_instructors",
        sa.Column(
            "class_type",
            sa.Enum(
                "LECTURE",
                "TUTORIALS",
                "LABORATORY",
                "SEMINAR",
                "OTHER",
                "ELEARNING",
                name="classtype",
            ),
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("uq_course_type_details_employee"),
        "courses_instructors",
        type_="unique",
    )

    op.create_foreign_key(
        "fk_courses_instructors_course_type_detail",
        "courses_instructors",
        "course_type_detail",
        ["course", "class_type"],
        ["course", "class_type"],
    )

    op.drop_column("courses_instructors", "id")
    op.drop_column("courses_instructors", "course_type_detail")

    op.drop_column("curriculum_courses", "id")
    op.create_primary_key(
        "pk_curriculum_courses",
        "curriculum_courses",
        ["study_program", "course", "semester"],
    )

    op.drop_column("group_members", "id")
    op.create_primary_key("pk_group_members", "group_members", ["group", "student"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group_members",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.create_unique_constraint(
        op.f("uq_group_members_group_id"),
        "group_members",
        ["group", "student"],
        postgresql_nulls_not_distinct=False,
    )
    op.add_column(
        "curriculum_courses",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.create_unique_constraint(
        op.f("uq_program_course_semester"),
        "curriculum_courses",
        ["study_program", "course", "semester"],
        postgresql_nulls_not_distinct=False,
    )
    op.add_column(
        "courses_instructors",
        sa.Column(
            "course_type_detail", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "courses_instructors",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_constraint(
        "fk_courses_instructors_course_type_detail",
        "courses_instructors",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("courses_instructors_course_type_detail_fkey"),
        "courses_instructors",
        "course_type_detail",
        ["course_type_detail"],
        ["id"],
    )
    op.create_unique_constraint(
        op.f("uq_course_type_details_employee"),
        "courses_instructors",
        ["course_type_detail", "employee"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("courses_instructors", "class_type")
    op.drop_column("courses_instructors", "course")
    op.add_column(
        "course_type_detail",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.create_unique_constraint(
        op.f("uq_course_class_type"),
        "course_type_detail",
        ["course", "class_type"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
