syntax = "proto3";

package user;
option go_package = "./internal/rpc/user;user";

service UserRpcService {
  rpc CreateUserRPC (UserCreateRequest) returns (UserCreateResponse);
  rpc DeleteUserRPC (UserDeleteRequest) returns (UserDeleteResponse);
  rpc GetUserRPC (UserGetRequest) returns (UserGetResponse);
}

message StudentProfile {
  int32 study_program_id = 1;
  int32 major_id = 2;
  int32 id = 3;
}

message EmployeeProfile {
  int32 faculty_id = 1;
  int32 unit_id = 2;
  int32 id = 3;
}

message UserCreateRequest {
  string email = 1;
  string name = 2;
  string surname = 3;
  string phone_number = 4;
  string degree = 5;
  bool send_login_credentials_email = 6;

  oneof profile {
    StudentProfile student = 7;
    EmployeeProfile employee = 8;
  }
}

message UserCreateResponse {
  int32 id = 1;
  string email = 2;
  string status = 3;
}

message UserDeleteRequest {
  int32 id = 1;
}

message UserDeleteResponse {
  bool success = 1;
  string message = 2;
}

message UserGetRequest {
  int32 id = 1;
}

message UserGetResponse {
  int32 id = 1;
  string email = 2;
  string name = 3;
  string surname = 4;
  string phone_number = 5;
  string degree = 6;

  oneof profile {
    StudentProfile student = 7;
    EmployeeProfile employee = 8;
  }
}