// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/academic-calendar": {
            "get": {
                "description": "Returns all academic calendar entries",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Academic Calendar"
                ],
                "summary": "Get academic calendar",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PaginatedAcademicCalendarResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new academic calendar record.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Academic Calendar"
                ],
                "summary": "Create academic calendar entry",
                "parameters": [
                    {
                        "description": "Academic calendar data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateAcademicCalendarRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.AcademicCalendarResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/buildings": {
            "get": {
                "description": "Returns list of buildings with number of rooms",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "buildings"
                ],
                "summary": "Get all buildings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PaginatedBuildingsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new building.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "buildings"
                ],
                "summary": "Create building",
                "parameters": [
                    {
                        "description": "Building data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateBuildingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Building"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/groups": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Get all groups",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Group"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateAcademicCalendarRequest": {
            "type": "object",
            "required": [
                "academic_day_of_week",
                "academic_year",
                "calendar_date",
                "semester_type",
                "week_number"
            ],
            "properties": {
                "academic_day_of_week": {
                    "type": "integer"
                },
                "academic_year": {
                    "type": "string"
                },
                "calendar_date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "semester_type": {
                    "type": "string"
                },
                "week_number": {
                    "type": "integer"
                }
            }
        },
        "dto.CreateBuildingRequest": {
            "type": "object",
            "required": [
                "building_name",
                "building_number",
                "campus_id"
            ],
            "properties": {
                "building_name": {
                    "type": "string"
                },
                "building_number": {
                    "type": "string"
                },
                "campus_id": {
                    "type": "integer"
                }
            }
        },
        "models.AcademicCalendarResponse": {
            "type": "object",
            "properties": {
                "academic_day_of_week": {
                    "type": "integer"
                },
                "academic_year": {
                    "type": "string"
                },
                "calendar_date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "semester_type": {
                    "type": "string"
                },
                "week_number": {
                    "type": "integer"
                }
            }
        },
        "models.Building": {
            "type": "object",
            "properties": {
                "building_name": {
                    "type": "string"
                },
                "building_number": {
                    "type": "string"
                },
                "campus_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.BuildingReadResponse": {
            "type": "object",
            "properties": {
                "building_name": {
                    "type": "string"
                },
                "building_number": {
                    "type": "string"
                },
                "campus_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "rooms_number": {
                    "type": "integer"
                }
            }
        },
        "models.Group": {
            "type": "object",
            "properties": {
                "elective_block": {
                    "type": "integer"
                },
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "major": {
                    "type": "integer"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GroupMember"
                    }
                },
                "semester": {
                    "type": "integer"
                },
                "study_program": {
                    "type": "integer"
                }
            }
        },
        "models.GroupMember": {
            "type": "object",
            "properties": {
                "group": {
                    "type": "integer"
                },
                "student": {
                    "type": "integer"
                }
            }
        },
        "models.PaginatedAcademicCalendarResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AcademicCalendarResponse"
                    }
                }
            }
        },
        "models.PaginatedBuildingsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BuildingReadResponse"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
