definitions:
  dto.CreateAcademicCalendarRequest:
    properties:
      academic_day_of_week:
        type: integer
      academic_year:
        type: string
      calendar_date:
        type: string
      description:
        type: string
      semester_type:
        type: string
      week_number:
        type: integer
    required:
    - academic_day_of_week
    - academic_year
    - calendar_date
    - semester_type
    - week_number
    type: object
  dto.CreateBuildingRequest:
    properties:
      building_name:
        type: string
      building_number:
        type: string
      campus_id:
        type: integer
    required:
    - building_name
    - building_number
    - campus_id
    type: object
  dto.CreateCampusRequest:
    properties:
      campus_name:
        type: string
      campus_short:
        type: string
    required:
    - campus_name
    - campus_short
    type: object
  dto.CreateCourseRequest:
    properties:
      course_code:
        type: integer
      course_coordinator:
        type: integer
      course_language:
        type: string
      course_name:
        type: string
      ects_points:
        type: integer
      leading_unit:
        type: integer
    required:
    - course_code
    - course_coordinator
    - course_language
    - course_name
    - ects_points
    - leading_unit
    type: object
  models.AcademicCalendarResponse:
    properties:
      academic_day_of_week:
        type: integer
      academic_year:
        type: string
      calendar_date:
        type: string
      description:
        type: string
      semester_type:
        type: string
      week_number:
        type: integer
    type: object
  models.Building:
    properties:
      building_name:
        type: string
      building_number:
        type: string
      campus_id:
        type: integer
      id:
        type: integer
    type: object
  models.BuildingReadResponse:
    properties:
      building_name:
        type: string
      building_number:
        type: string
      campus_id:
        type: integer
      id:
        type: integer
      rooms_number:
        type: integer
    type: object
  models.Campus:
    properties:
      campus_name:
        type: string
      campus_short:
        type: string
      id:
        type: integer
    type: object
  models.Course:
    properties:
      course_code:
        type: integer
      course_coordinator:
        type: integer
      course_language:
        type: string
      course_name:
        type: string
      ects_points:
        type: integer
      leading_unit:
        type: integer
    type: object
  models.Group:
    properties:
      elective_block:
        type: integer
      group_name:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      major:
        type: integer
      members:
        items:
          $ref: '#/definitions/models.GroupMember'
        type: array
      semester:
        type: integer
      study_program:
        type: integer
    type: object
  models.GroupMember:
    properties:
      group:
        type: integer
      student:
        type: integer
    type: object
  models.PaginatedAcademicCalendarResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.AcademicCalendarResponse'
        type: array
    type: object
  models.PaginatedBuildingsResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.BuildingReadResponse'
        type: array
    type: object
  models.PaginatedCampusesResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.Campus'
        type: array
    type: object
  models.PaginatedCoursesResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.Course'
        type: array
    type: object
info:
  contact: {}
paths:
  /academic-calendar:
    get:
      description: Returns all academic calendar entries
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaginatedAcademicCalendarResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get academic calendar
      tags:
      - Academic Calendar
    post:
      consumes:
      - application/json
      description: Creates a new academic calendar record.
      parameters:
      - description: Academic calendar data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateAcademicCalendarRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.AcademicCalendarResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create academic calendar entry
      tags:
      - Academic Calendar
  /buildings:
    get:
      description: Returns list of buildings with number of rooms
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaginatedBuildingsResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all buildings
      tags:
      - buildings
    post:
      consumes:
      - application/json
      description: Creates a new building.
      parameters:
      - description: Building data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateBuildingRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Building'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create building
      tags:
      - buildings
  /campuses:
    get:
      description: Returns list of all campuses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaginatedCampusesResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all campuses
      tags:
      - campuses
    post:
      consumes:
      - application/json
      description: Creates a new campus.
      parameters:
      - description: Campus data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCampusRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Campus'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create campus
      tags:
      - campuses
  /courses:
    get:
      description: Returns list of all courses sorted by course code
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaginatedCoursesResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all courses
      tags:
      - courses
    post:
      consumes:
      - application/json
      description: Creates a new course.
      parameters:
      - description: Course data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCourseRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Course'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create course
      tags:
      - courses
  /groups:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Group'
            type: array
      summary: Get all groups
      tags:
      - groups
swagger: "2.0"
