import os
from openpyxl import load_workbook, Workbook

from backend.src.users.models import Users
from backend.src.academics.models import Employees, Units
from backend.src.facilities.models import Faculty


class ExcelWriter:
    def __init__(self, filename: str):
        self.filename = filename

        if os.path.exists(filename):
            self.wb = load_workbook(filename)
            self.ws = self.wb.active
        else:
            self.wb = Workbook()
            self.ws = self.wb.active

    def write_row(self, data: list):
        self.ws.append(data)

    def save(self):
        self.wb.save(self.filename)


def _get_employee_object_by_user_id(
    db_employees: dict[tuple[str | None, str, str], Employees], user_id: int
):
    for employee in db_employees.values():
        if employee.user_id == user_id:
            return employee
    return None


def _get_unit_name_by_id(db_units: dict[str, Units], unit_id: int):
    for unit in db_units.values():
        if unit.id == unit_id:
            return unit.unit_name
    return None


def _get_faculty_by_id(db_faculties: dict[str, Faculty], faculty_id: int):
    for faculty in db_faculties.values():
        if faculty.id == faculty_id:
            return faculty.faculty_name
    return None


def save_teachers_to_excel(
    filename: str,
    db_teachers: dict[tuple[str | None, str, str, str, str], Users],
    db_faculties: dict[str, Faculty],
    db_units: dict[str, Units],
    db_employees: dict[tuple[str | None, str, str], Employees],
):
    """
    Saves information about teachers in excel file
    :param filename: filename of excel file
    :param db_teachers: user objects representing teachers generated by generate_users
    :param db_faculties: faculties generated by generate_faculties
    :param db_units: units generated by generate_units
    :param db_employees: employees generated by generate_employees
    :return: None
    """
    excel = ExcelWriter(filename)

    excel.write_row(
        ["Name", "Surname", "Degree", "Email", "Password", "Faculty", "Unit"]
    )

    for user_desc, user_obj in db_teachers.items():
        name = user_obj.name
        surname = user_obj.surname
        degree = user_obj.degree
        email = user_obj.email
        password = user_desc[4]

        faculty = None
        unit = None

        emp_obj = _get_employee_object_by_user_id(db_employees, user_obj.id)
        if emp_obj:
            faculty = _get_faculty_by_id(db_faculties, emp_obj.faculty_id)
            unit = _get_unit_name_by_id(db_units, emp_obj.unit_id)
        else:
            print("Not found employee")

        excel.write_row([name, surname, degree, email, password, faculty, unit])

    excel.save()


def save_not_teachers_to_excel(
    filename: str,
    db_not_teachers: dict[tuple[str | None, str, str, str, str, bool], Users],
):
    """
    Saves information about teachers in excel file
    :param filename: filename of excel file
    :param db_not_teachers: user objects representing not teachers generated by generate_users
    :return: None
    """
    excel = ExcelWriter(filename)

    excel.write_row(["Name", "Surname", "Degree", "Email", "Password"])

    for user_desc, user_obj in db_not_teachers.items():
        name = user_obj.name
        surname = user_obj.surname
        degree = user_obj.degree
        email = user_obj.email
        password = user_desc[4]

        excel.write_row([name, surname, degree, email, password])

    excel.save()
