from typing import Callable

from sqlalchemy.orm import Session

from backend.src.users.models import Users, Roles


def _get_admin_role_obj(roles: dict[str, Roles]) -> Roles:
    admin_obj = roles.get("Administrator", None)
    if admin_obj is None:
        raise Exception("No Administrator role found")
    return admin_obj


def create_user_admin(
    session: Session,
    password_hash_func: Callable[[str], str] | None,
    roles: dict[str, Roles],
):
    """
    Create an admin user
    :param session: database session
    :param password_hash_func: hash function for passwords
        (in case of None, hash is the same as plain password)
    :param roles: dictionary mapping role names to Roles objects
        (generated by generate_roles_from_excel_file)
    :return: Admin User object
    """
    if password_hash_func is None:

        def not_a_hash(text: str) -> str:
            return text

        password_hash_func = not_a_hash

    mail = "admin@nimda.pl"
    password = "qwerty"
    password_hash = password_hash_func(password)
    name = "Admin"
    surname = "Adminkowski"
    admin_role_obj = _get_admin_role_obj(roles)

    user_obj = Users(
        password_hash=password_hash,
        email=mail,
        phone_number="123456789",
        name=name,
        surname=surname,
        degree=None,
        roles=[admin_role_obj],
        email_verified=True,
    )

    session.add(user_obj)
    session.flush()
    return user_obj
