import random

from sqlalchemy.orm import Session

from backend.src.academics.models import Units, Employees
from backend.src.facilities.models import Faculty
from backend.src.users.models import Users


def _get_random_unit_id(db_units: dict[str, Units]) -> int:
    """
    Get a random unit id from the database
    :param db_units: units
    :return: random unit id
    """
    keys = list(db_units.keys())
    r = random.choice(keys)
    return db_units[r].id


def _get_random_faculty_id(db_faculties: dict[str, Faculty]) -> int:
    """
    Get a random faculty id from the database
    :param db_faculties: faculties
    :return: random faculty id
    """
    keys = list(db_faculties.keys())
    r = random.choice(keys)
    return db_faculties[r].id


def _get_user_id(user: Users) -> int:
    """
    Get a user id
    :param user: user
    :return: user id
    """
    return user.id


def _get_user_info(user: Users) -> tuple[str | None, str, str]:
    """
    Get a user info
    :param user: user
    :return: degree, name, surname
    """
    return user.degree, user.name, user.surname


def generate_employees(
    session: Session,
    db_teachers: dict[tuple[str | None, str, str, str, str], Users],
    db_units: dict[str, Units],
    db_faculties: dict[str, Faculty],
) -> dict[tuple[str | None, str, str], Employees]:
    """
    Generate employees
    :param session: database session
    :param db_teachers: teachers generated by generate_users
    :param db_units: units generated by generate_units
    :param db_faculties: faculties generated by generate_faculties
    :return: dict mapping (degree, name, surname) to Employees object
    """
    db_employees: dict[tuple[str | None, str, str], Employees] = {}

    # for teacher in db_teachers:
    ti = db_teachers.items()
    for _, v in ti:
        user_id = _get_user_id(v)
        faculty_id = _get_random_faculty_id(db_faculties)
        unit_id = _get_random_unit_id(db_units)
        employee = Employees(
            user_id=user_id,
            faculty_id=faculty_id,
            unit_id=unit_id,
        )
        session.add(employee)
        info = _get_user_info(v)
        db_employees[(info[0], info[1], info[2])] = employee

    session.flush()
    return db_employees
