from sqlalchemy.orm import Session

from backend.src.academics.models import Units
from backend.src.facilities.models import Campus, Building, Faculty, Room


def generate_campuses(session: Session) -> dict[str, Campus]:
    """
    Generates campuses and adds them to the database session.
    :param session: database session
    :return: a dictionary mapping campus short names to Campus objects
    """
    campuses = [
        {"campus_short": "A", "campus_name": "Kampus A"},
        {"campus_short": "B", "campus_name": "Kampus B"},
        {"campus_short": "C", "campus_name": "Kampus C"},
    ]

    db_campuses: dict[str, Campus] = {}

    for campus in campuses:
        campus_data = Campus(**campus)
        session.add(campus_data)
        db_campuses[campus_data.campus_short] = campus_data

    session.flush()

    return db_campuses


def generate_faculties(session: Session) -> dict[str, Faculty]:
    """
    Generates faculties and adds them to the database session.
    :param session: database session
    :return: a dictionary mapping faculty short names to Faculty objects
    """
    faculties_data: list[dict[str, str]] = [
        {
            "faculty_name": "Wydział Elektrotechniki, Elektroniki, Informatyki i Automatyki",
            "faculty_short": "WEEIA",
        },
        {
            "faculty_name": "Wydział Mechaniczny",
            "faculty_short": "WM",
        },
        {
            "faculty_name": "Wydział Fizyki Technicznej, Informatyki i Matematyki Stosowanej",
            "faculty_short": "WFTIMS",
        },
        {
            "faculty_name": "Wydział Organizacji i Zarządzania",
            "faculty_short": "WOIZ",
        },
        {
            "faculty_name": "Wydział Biotechnologii i Nauk o Żywności",
            "faculty_short": "WBINOŻ",
        },
        {
            "faculty_name": "Wydział Chemiczny",
            "faculty_short": "Wch",
        },
    ]
    db_faculties: dict[str, Faculty] = {}
    for faculty in faculties_data:
        faculty_data = Faculty(**faculty)
        session.add(faculty_data)
        db_faculties[faculty_data.faculty_short] = faculty_data

    session.flush()
    return db_faculties


def generate_buildings(
    session: Session, campuses: dict[str, Campus]
) -> dict[str, Building]:
    """
    Generates buildings and adds them to the database session.
    NOTE! REMEMBER TO ADD FACULTIES
    :param session: database session
    :param campuses: campuses
    :return: a dictionary mapping campus short names to Building objects
    """
    buildings_map: dict[str, list[str]] = {
        "A": ["A7", "A10", "A11", "A12a", "A12b", "A15"],
        "B": ["B9", "B18", "B19"],
        "C": ["C3", "C6", "C8"],
    }

    db_buildings: dict[str, Building] = {}

    for campus in campuses.values():
        target_buildings = buildings_map.get(campus.campus_short, [])

        for building_number in target_buildings:
            building = Building(building_number=building_number, campus_id=campus.id)
            session.add(building)
            db_buildings[building_number] = building

    session.flush()
    return db_buildings


def generate_rooms(
    session: Session,
    faculties: dict[str, Faculty],
    units: dict[str, Units],
    buildings: dict[str, Building],
) -> dict[str, Room]:
    """
    Generates rooms and adds them to the database session.
    :param session: database session
    :param faculties: faculties
    :param units: units
    :param buildings: buildings
    :return: a dictionary mapping rooms short names to Room objects
    """
    room_map: list[dict[str, any]] = [
        {
            "room_name": "E1",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 250,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "E2",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 220,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "E5",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 170,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "E6",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 170,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "E102",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 35,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "E103",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 35,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "E104",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 35,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "E105",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 35,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "E106",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 35,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "E123",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "E3",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "E4",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 408",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 A12a/we2 147",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A12a",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 A12a/we2 23",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A12a",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 A12a/we2 RiS",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A12a",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 B.A7",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A12b",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 C3 402 St",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 C3 403",
            "projector_availability": True,
            "pc_amount": 30,
            "room_capacity": 30,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 C3 404",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 50,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 C3 410",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 C3 411",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 C3 412",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 E10",
            "projector_availability": True,
            "pc_amount": 30,
            "room_capacity": 30,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 E100",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 E101",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 E101",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 E406",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 E408",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 E9",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 E9 PLC",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i21 ssem",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 50,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I21",
        },
        {
            "room_name": "i22 A11 101",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 A11 204",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 A11 215",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 70,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 A11 216",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 30,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 A11 225",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 30,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 A11 226",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 30,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 A11 309",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 30,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 A11 315",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 30,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 A11 321",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 30,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 A11 323",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 70,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 A11 WN lab",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 C3 013",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 C3 018",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 C3 04",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 C3 05",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 C3 06",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 C3 ZE",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 80,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 C3 ZE lab",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 C3 ZE PC",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i22 C3 ZTiPE ssem",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 50,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I22",
        },
        {
            "room_name": "i23 415",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 50,
            "building_short": "B9",
            "faculty_short": "WEEIA",
            "unit_short": "I23",
        },
        {
            "room_name": "i23 416",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 50,
            "building_short": "B9",
            "faculty_short": "WEEIA",
            "unit_short": "I23",
        },
        {
            "room_name": "i23 113",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 50,
            "building_short": "B9",
            "faculty_short": "WEEIA",
            "unit_short": "I23",
        },
        {
            "room_name": "i23 204",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 30,
            "building_short": "B9",
            "faculty_short": "WEEIA",
            "unit_short": "I23",
        },
        {
            "room_name": "i23 204A",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B9",
            "faculty_short": "WEEIA",
            "unit_short": "I23",
        },
        {
            "room_name": "i23 214",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B9",
            "faculty_short": "WEEIA",
            "unit_short": "I23",
        },
        {
            "room_name": "i23 215",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B9",
            "faculty_short": "WEEIA",
            "unit_short": "I23",
        },
        {
            "room_name": "i23 320A",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 40,
            "building_short": "B9",
            "faculty_short": "WEEIA",
            "unit_short": "I23",
        },
        {
            "room_name": "i23 321A",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B9",
            "faculty_short": "WEEIA",
            "unit_short": "I23",
        },
        {
            "room_name": "i23 409",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "B9",
            "faculty_short": "WEEIA",
            "unit_short": "I23",
        },
        {
            "room_name": "i23 413",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B9",
            "faculty_short": "WEEIA",
            "unit_short": "I23",
        },
        {
            "room_name": "i24 107",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 30,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 108",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 30,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 109",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 110",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 307",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 311",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 30,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 A15",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 50,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 B19 403",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B19",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 B19 404",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B19",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 B19 405",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B19",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 B19 406",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B19",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 B19 407",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B19",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 B19 409",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B19",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 C3 14",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 C6 09",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "C6",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i24 C6 115",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "C6",
            "faculty_short": "WEEIA",
            "unit_short": "I24",
        },
        {
            "room_name": "i25 132",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I25",
        },
        {
            "room_name": "i25 133",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I25",
        },
        {
            "room_name": "i25 134",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I25",
        },
        {
            "room_name": "i25 135",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I25",
        },
        {
            "room_name": "i25 bud.A7",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 40,
            "building_short": "A7",
            "faculty_short": "WEEIA",
            "unit_short": "I25",
        },
        {
            "room_name": "i25 IBM",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I25",
        },
        {
            "room_name": "i25 l.AGD",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I25",
        },
        {
            "room_name": "i25 l.elen",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I25",
        },
        {
            "room_name": "i25 l.m.el. 1",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I25",
        },
        {
            "room_name": "i25 l.mechatroniki",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I25",
        },
        {
            "room_name": "i25 l.proj.inż",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I25",
        },
        {
            "room_name": "i25 ZPiKE 1",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I25",
        },
        {
            "room_name": "i25 ZPiKE 2",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I25",
        },
        {
            "room_name": "i25 ZPiKE EMC",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "I25",
        },
        {
            "room_name": "i26 208",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A15",
            "faculty_short": "WEEIA",
            "unit_short": "I26",
        },
        {
            "room_name": "i26 212",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A15",
            "faculty_short": "WEEIA",
            "unit_short": "I26",
        },
        {
            "room_name": "i26 222",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A15",
            "faculty_short": "WEEIA",
            "unit_short": "I26",
        },
        {
            "room_name": "i26 415 kl.2",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A15",
            "faculty_short": "WEEIA",
            "unit_short": "I26",
        },
        {
            "room_name": "i26 501 kl.2",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A15",
            "faculty_short": "WEEIA",
            "unit_short": "I26",
        },
        {
            "room_name": "i26 502 kl.1",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A15",
            "faculty_short": "WEEIA",
            "unit_short": "I26",
        },
        {
            "room_name": "i26 C3 105",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 30,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I26",
        },
        {
            "room_name": "i26 C3 109",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 30,
            "building_short": "C3",
            "faculty_short": "WEEIA",
            "unit_short": "I26",
        },
        {
            "room_name": "i26 E8",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "A10",
            "faculty_short": "WEEIA",
            "unit_short": "I26",
        },
        {
            "room_name": "k21 A11 418",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 100,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "K21",
        },
        {
            "room_name": "k21 A11 408a",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "K21",
        },
        {
            "room_name": "k21 A11 408b",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "K21",
        },
        {
            "room_name": "k21 A11 414",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A11",
            "faculty_short": "WEEIA",
            "unit_short": "K21",
        },
        {
            "room_name": "k21 A12 149",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A12b",
            "faculty_short": "WEEIA",
            "unit_short": "K21",
        },
        {
            "room_name": "k21 A12 156",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A12b",
            "faculty_short": "WEEIA",
            "unit_short": "K21",
        },
        {
            "room_name": "k21 A12 201",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A12b",
            "faculty_short": "WEEIA",
            "unit_short": "K21",
        },
        {
            "room_name": "k21 A12 202",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A12b",
            "faculty_short": "WEEIA",
            "unit_short": "K21",
        },
        {
            "room_name": "k21 A12a/we1 156",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A12a",
            "faculty_short": "WEEIA",
            "unit_short": "K21",
        },
        {
            "room_name": "k21 A12a/we1 216",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 20,
            "building_short": "A12a",
            "faculty_short": "WEEIA",
            "unit_short": "K21",
        },
        {
            "room_name": "k22 B18 A1",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 200,
            "building_short": "B18",
            "faculty_short": "WEEIA",
            "unit_short": "K22",
        },
        {
            "room_name": "k22 B18 A2",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 200,
            "building_short": "B18",
            "faculty_short": "WEEIA",
            "unit_short": "K22",
        },
        {
            "room_name": "k22 B18 A3",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 100,
            "building_short": "B18",
            "faculty_short": "WEEIA",
            "unit_short": "K22",
        },
        {
            "room_name": "k22 B18 A4",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 100,
            "building_short": "B18",
            "faculty_short": "WEEIA",
            "unit_short": "K22",
        },
        {
            "room_name": "k22 B18 A5",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 100,
            "building_short": "B18",
            "faculty_short": "WEEIA",
            "unit_short": "K22",
        },
        {
            "room_name": "k22 B18 I.A",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B18",
            "faculty_short": "WEEIA",
            "unit_short": "K22",
        },
        {
            "room_name": "k22 B18 I.B",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B18",
            "faculty_short": "WEEIA",
            "unit_short": "K22",
        },
        {
            "room_name": "k22 B18 I.C",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B18",
            "faculty_short": "WEEIA",
            "unit_short": "K22",
        },
        {
            "room_name": "k22 B18 I.D",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B18",
            "faculty_short": "WEEIA",
            "unit_short": "K22",
        },
        {
            "room_name": "k22 B18 I.M",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B18",
            "faculty_short": "WEEIA",
            "unit_short": "K22",
        },
        {
            "room_name": "k22 B18 I.PPM",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B18",
            "faculty_short": "WEEIA",
            "unit_short": "K22",
        },
        {
            "room_name": "k22 B18 I.ZK",
            "projector_availability": True,
            "pc_amount": 20,
            "room_capacity": 20,
            "building_short": "B18",
            "faculty_short": "WEEIA",
            "unit_short": "K22",
        },
        {
            "room_name": "k22 B19 301",
            "projector_availability": True,
            "pc_amount": 0,
            "room_capacity": 50,
            "building_short": "B19",
            "faculty_short": "WEEIA",
            "unit_short": "K22",
        },
    ]
    db_rooms: dict[str, Room] = {}

    for room in room_map:
        target_faculty = faculties.get(room.get("faculty_short"))
        if not target_faculty:
            print("Wrong faculty short")
            continue
        target_building = buildings.get(room.get("building_short"))
        if not target_building:
            print("Wrong building short")
            continue
        target_unit = None
        unit_short = room.get("unit_short")
        if unit_short:
            target_unit = units.get(unit_short)

        new_room = Room(
            room_name=room.get("room_name"),
            projector_availability=room.get("projector_availability"),
            pc_amount=room.get("pc_amount"),
            room_capacity=room.get("room_capacity"),
            building_id=target_building.id,
            faculty_id=target_faculty.id,
            unit_id=target_unit.id if target_unit else None,
        )
        session.add(new_room)
        db_rooms[room["room_name"]] = new_room
