from sqlalchemy.orm import Session

from backend.src.academics.models import Students, Groups, Group_members
from backend.src.courses.models import Study_program


def _map_students_to_study_programs(
    db_students: dict[tuple[str, str | None, str | None], Students],
) -> dict[int, list[Students]]:
    mapping: dict[int, list[Students]] = {}
    for s_obj in db_students.values():
        sp_id = s_obj.study_program

        if sp_id not in mapping:
            mapping[sp_id] = []

        l = mapping[sp_id]
        l.append(s_obj)
        mapping[sp_id] = l

    return mapping


def _get_study_program_name_by_id(
    db_study_programs: dict[tuple[str, str, int], Study_program], sp_id: int
) -> str | None:
    for sp_obj in db_study_programs.values():
        if sp_obj.id == sp_id:
            return sp_obj.program_name
    return "error"


def _generate_common_group_name(study_program_name: str | None, num: int) -> str:
    return f"{study_program_name} #{num}"


def generate_common_groups(
    session: Session,
    db_students: dict[tuple[str, str | None, str | None], Students],
    db_study_programs: dict[tuple[str, str, int], Study_program],
    group_size: int = 15,
) -> dict[str, Groups]:
    """
    Generates common groups
    :param session: database session
    :param db_students: student data generated by generate_students
    :param db_study_programs: study programs generated by generate_study_programs
    :param group_size: group size
    :return: dict mapping group names to Groups objects
    """

    db_common_groups: dict[str, Groups] = {}

    mapped_students: dict[int, list[Students]] = _map_students_to_study_programs(
        db_students
    )

    for sp_id in mapped_students.keys():
        students_in_sp: list = mapped_students[sp_id]
        num_of_students = len(students_in_sp)
        num_of_groups = (num_of_students + group_size - 1) // group_size
        sp_name = _get_study_program_name_by_id(db_study_programs, sp_id)

        for i in range(1, num_of_groups + 1):
            group_name = _generate_common_group_name(sp_name, i)

            group_obj = Groups(
                group_name=group_name,
                study_program=sp_id,
                major=None,
                elective_block=None,
            )
            session.add(group_obj)
            db_common_groups[group_name] = group_obj

    session.flush()
    return db_common_groups


def _map_groups_to_study_programs(db_common_groups: dict[str, Groups]):
    mapping: dict[int, list[Groups]] = {}
    for g_obj in db_common_groups.values():
        sp_id = g_obj.study_program
        if sp_id not in mapping:
            mapping[sp_id] = []

        l = mapping[sp_id]
        l.append(g_obj)
        mapping[sp_id] = l

    return mapping


def assign_students_to_common_groups(
    session: Session,
    db_common_groups: dict[str, Groups],
    db_students: dict[tuple[str, str | None, str | None], Students],
    db_study_programs: dict[tuple[str, str, int], Study_program],
    group_size: int = 15,
):
    """
    Assigns students to common groups by creating Group_members objects
    :param session: database session
    :param db_common_groups: common groups generated by generate_common_groups
    :param db_students: student data generated by generate_students
    :param db_study_programs: study programs generated by generate_study_programs
    :param group_size: group size
    :return: dict mapping group_id and student_id to Group_members objects
    """
    db_common_group_members: dict[tuple[int, int], Group_members] = {}

    mapped_students: dict[int, list[Students]] = _map_students_to_study_programs(
        db_students
    )
    mapped_groups: dict[int, list[Groups]] = _map_groups_to_study_programs(
        db_common_groups
    )

    for sp_obj in db_study_programs.values():
        sp_id = sp_obj.id
        sp_students = mapped_students[sp_id]
        sp_groups = mapped_groups[sp_id]

        num_of_students = len(sp_students)
        # num_of_groups = len(sp_groups)

        s_idx = 0
        exit_cond = False
        for group_obj in sp_groups:
            for i in range(1, group_size + 1):
                curr_student_obj = sp_students[s_idx]
                s_idx += 1

                gm_obj = Group_members(
                    group=group_obj.id,
                    student=curr_student_obj.id,
                )
                session.add(gm_obj)
                db_common_group_members[(group_obj.id, curr_student_obj.id)] = gm_obj

                if s_idx >= num_of_students:
                    exit_cond = True
                    break
            if exit_cond:
                break

    return db_common_group_members
