from sqlalchemy.orm import Session

from backend.src.academics.models import Students, Groups
from backend.src.courses.models import Study_program


def _map_students_to_study_programs(
    db_students: dict[tuple[str, str | None, str | None], Students],
) -> dict[int, list[Students]]:
    mapping: dict[int, list[Students]] = {}
    for s_obj in db_students.values():
        sp_id = s_obj.study_program

        if sp_id not in mapping:
            mapping[sp_id] = []

        l = mapping[sp_id]
        l.append(s_obj)
        mapping[sp_id] = l

    return mapping


def _get_study_program_name_by_id(
    db_study_programs: dict[tuple[str, str, int], Study_program], sp_id: int
) -> str | None:
    for sp_obj in db_study_programs.values():
        if sp_obj.id == sp_id:
            return sp_obj.program_name
    return "error"


def _generate_common_group_name(study_program_name: str | None, num: int) -> str:
    return f"{study_program_name} #{num}"


def generate_common_groups(
    session: Session,
    db_students: dict[tuple[str, str | None, str | None], Students],
    db_study_programs: dict[tuple[str, str, int], Study_program],
    group_size: int = 15,
) -> dict[str, Groups]:
    """
    Generates common groups
    :param session: database session
    :param db_students: student data generated by generate_students
    :param db_study_programs: study programs generated by generate_study_programs
    :param group_size: group size
    :return: dict mapping group names to Groups objects
    """

    db_common_groups: dict[str, Groups] = {}

    mapped_students: dict[int, list[Students]] = _map_students_to_study_programs(
        db_students
    )

    for sp_id in mapped_students.keys():
        students_in_sp: list = mapped_students[sp_id]
        num_of_students = len(students_in_sp)
        num_of_groups = (num_of_students + group_size - 1) // group_size
        sp_name = _get_study_program_name_by_id(db_study_programs, sp_id)

        for i in range(1, num_of_groups + 1):
            group_name = _generate_common_group_name(sp_name, i)

            group_obj = Groups(
                group_name=group_name,
                study_program=sp_id,
                major=None,
                elective_block=None,
            )
            session.add(group_obj)
            db_common_groups[group_name] = group_obj

    session.flush()
    return db_common_groups
