from sqlalchemy.orm import Session

from backend.src.users.models import Users
from backend.src.academics.models import Students
from backend.src.courses.models import Study_program, Curriculum_course, Major


def _get_only_students(
    db_users: dict[tuple[str | None, str, str, str, str, bool], Users],
):
    students: dict[tuple[str | None, str, str, str, str], Users] = {}
    for key in db_users:
        if key[5]:
            new_key = (key[0], key[1], key[2], key[3], key[4])
            students[new_key] = db_users[key]
    return students


def _get_all_study_programs_with(
    study_field_name: str,
    degree: int,
    db_study_programs: dict[tuple[str, str, int], Study_program],
):
    res = []
    for obj in db_study_programs.values():
        if (
            study_field_name in obj.program_name
            and f"{degree}. stopień" in obj.program_name
        ):
            res.append(obj)
    return res


def _get_majors_from_study_program(
    study_program: Study_program,
    db_curr_courses: dict[
        tuple[str | None, int, int, str | None, str | None], Curriculum_course
    ],
):
    majors_ids = set()

    sp_id = study_program.id
    for cc_obj in db_curr_courses.values():
        if cc_obj.study_program == sp_id and cc_obj.major:
            majors_ids.add(cc_obj.major)

    return list(majors_ids)


def _assign_students_to_study_program(
    amount_of_students: dict,
    students: dict[tuple[str | None, str, str, str, str], Users],
    db_study_programs: dict[tuple[str, str, int], Study_program],
    db_curr_courses: dict[
        tuple[str | None, int, int, str | None, str | None], Curriculum_course
    ],
):
    students_objs = []
    users_list = list(students.values())
    idx = 0

    for study_field_name, degree in amount_of_students:
        for sp in _get_all_study_programs_with(
            study_field_name, degree, db_study_programs
        ):
            majors_ids = _get_majors_from_study_program(sp, db_curr_courses)
            if not majors_ids:
                majors_ids = [None]
            m_idx = 0
            len_majors = len(majors_ids)

            amount = amount_of_students[(study_field_name, degree)]
            while amount > 0:
                amount -= 1
                user_obj = users_list[idx]
                idx += 1
                student_obj = Students(
                    user_id=user_obj.id,
                    study_program=sp.id,
                    major=majors_ids[m_idx % len_majors],
                )
                m_idx += 1
                students_objs.append(student_obj)
    return students_objs


def _get_major_name_by_id(
    db_majors: dict[tuple[str, str], Major], m_id: int | None
) -> str | None:
    if m_id is None:
        return None
    for major_obj in db_majors.values():
        if major_obj.id == m_id:
            return major_obj.major_name
    return None


def _get_email_by_user_id(
    db_not_teachers: dict[tuple[str | None, str, str, str, str, bool], Users], u_id: int
) -> str:
    for user_obj in db_not_teachers.values():
        if user_obj.id == u_id:
            return user_obj.email
    raise KeyError(f"User with id {u_id} not found")


def _get_study_program_name_by_id(
    db_study_programs: dict[tuple[str, str, int], Study_program], sp_id: int
) -> str | None:
    for sp_obj in db_study_programs.values():
        if sp_obj.id == sp_id:
            return sp_obj.program_name
    raise KeyError(f"Study program with id {sp_id} not found")


def generate_students(
    session: Session,
    db_not_teachers: dict[tuple[str | None, str, str, str, str, bool], Users],
    db_study_programs: dict[tuple[str, str, int], Study_program],
    db_curr_courses: dict[
        tuple[str | None, int, int, str | None, str | None], Curriculum_course
    ],
    db_majors: dict[tuple[str, str], Major],
) -> dict[tuple[str, str | None, str | None], Students]:
    """
    Generates Students objects by assigning Users to study programs and majors
    :param session: database session
    :param db_not_teachers: not teacher users generated by generate_users
    :param db_study_programs: study programs generated by generate_study_programs
    :param db_curr_courses: curriculum courses generated by generate_curriculum_courses
    :return: students
    """
    db_students: dict[tuple[str, str | None, str | None], Students] = {}
    # email, study_program_name, major_name
    amount_of_students: dict = {
        ("Automatyka i sterowanie robotów", 1): 50,
        ("Biomedical engineering and technologies", 1): 50,
        ("Computer science", 1): 50,
        ("Computer science and information technology", 2): 30,
        ("Elektronika i telekomunikacja", 1): 50,
        ("Elektrotechnika", 2): 50,
        ("Informatyka", 1): 150,
        ("Informatyka", 2): 100,
    }
    students = _get_only_students(db_not_teachers)
    students_objs = _assign_students_to_study_program(
        amount_of_students, students, db_study_programs, db_curr_courses
    )
    for s_obj in students_objs:
        session.add(s_obj)

        email = _get_email_by_user_id(db_not_teachers, s_obj.user_id)
        major = _get_major_name_by_id(db_majors, s_obj.major)
        program_name = _get_study_program_name_by_id(db_study_programs, s_obj.study_program)
        db_students[(email, program_name, major)] = s_obj
    session.flush()
    return db_students
