import random
from typing import Callable
from faker import Faker


from sqlalchemy.orm import Session
from backend.src.users.models import Users, Roles


def _generate_full_names(
    n: int, seed: int | None = None, with_duplicates: bool = False
) -> list[tuple[str, str]]:
    """
    Generates a list of full names by randomly combining names and surnames.
    :param n: number of full names
    :param seed: seed for the random generator to produce reproducible results. Default is None.
    :param with_duplicates: If True, allows duplicate full names in the output list.
        If False, ensures all full names are unique. Default is False.
    :return: list of full names
    """

    fake = Faker("pl_PL")
    if seed is not None:
        Faker.seed(seed)

    if not with_duplicates:
        result = set()
        while len(result) < n:
            result.add((fake.first_name(), fake.last_name()))

        result = list(result)
        result.sort()
        return result
    else:
        result = []
        for _ in range(n):
            result.append((fake.first_name(), fake.last_name()))
        result.sort()
        return result


def _generate_email(name: str, surname: str, domain: str) -> str:
    """
    Generates an email address from name and surname
    :param name: name of email
    :param surname: surname of email
    :param domain: domain of email
    :return: email address
    """

    def _replace_polish_chars(text: str) -> str:
        mapping = {
            "ą": "a",
            "ć": "c",
            "ę": "e",
            "ł": "l",
            "ń": "n",
            "ó": "o",
            "ś": "s",
            "ż": "z",
            "ź": "z",
        }
        return "".join(mapping.get(c, c) for c in text)

    def _normalize(text: str) -> str:
        text = text.strip().lower()
        return _replace_polish_chars(text)

    name = name[:3]

    name = _normalize(name)
    surname = _normalize(surname)
    domain = _normalize(domain)

    random_num = random.randint(1000, 9999)

    return f"{name}.{surname}.{random_num}@{domain}"


def _generate_unique_phone_numbers(n: int, phone_len: int = 9) -> list[str]:
    """
    Generates a list of unique phone numbers
    :param n: number of phone numbers
    :param phone_len: phone number length
    :return: list of unique phone numbers
    """
    max_combinations = 10**phone_len

    if n > max_combinations:
        raise ValueError("Not enough unique combinations")

    numbers = set()
    while len(numbers) < n:
        num = random.randint(0, 999_999_999)
        formatted = f"{num:09d}"
        numbers.add(formatted)

    return list(numbers)


def _generate_password(name: str, surname: str) -> str:
    """
    Generates a simple password from name and surname
    :param name: name of user
    :param surname: surname of user
    :return: simple password
    """
    name = name.strip().lower()
    surname = surname.strip().lower()
    return f"{name}{surname}"


def _sum_values(d: dict[str, int]) -> int:
    """
    Calculate sum of dictionary values
    :param d: dictionary
    :return: sum of dictionary values
    """
    sum: int = 0
    for k in d.keys():
        sum += d[k]
    return sum


def _expand_roles(num_of_roles: dict[str, int]) -> list[str]:
    """
    Creates a list of roles based on a dictionary where keys are role
        names and values are the number of users with that role.
    :param num_of_roles: dictionary where keys are role names and values
        are number of users with that role.
    :return: list of roles
    """
    return [role for role, count in num_of_roles.items() for _ in range(count)]


def generate_users(
    session: Session,
    roles: dict[str, Roles],
    num_of_roles_not_teachers: dict[str, int],
    teachers: list[dict[str, str]],
    total_not_teacher_new_users: int,
    seed: int | None,
    password_hash_func: Callable[[str], str] | None,
    not_teacher_email_domain: str,
    teacher_email_domain: str,
) -> tuple[
    dict[tuple[str | None, str, str, str, str], Users],
    dict[tuple[str | None, str, str, str, str, bool], Users],
]:
    """
    Generates a list of users (teachers and others)
    :param session: database session
    :param roles: dictionary mapping role names to Roles objects
        (generated by generate_roles_from_excel_file)
    :param num_of_roles_not_teachers: dictionary where keys are
        role names and values are number of users with that role.
    :param teachers: list of teachers generated by extract_teachers function
    :param total_not_teacher_new_users: number of not teacher users
    :param seed: seed for the random generator to produce reproducible results
    :param password_hash_func: hash function for passwords
        (in case of None, hash is the same as plain password)
    :param not_teacher_email_domain: domain for not teacher email
    :param teacher_email_domain: domain for teacher email
    :return: A tuple containing two dictionaries.
        Each dictionary maps a key, represented as a tuple of
        (degree, name, surname, email, password), to a Users object.
        First dictionary contains teachers.
        Second dictionary contains non-teachers.
    """

    # list[dict[tuple[degree, name, surname, email, password], Users]]
    db_teachers: dict[tuple[str | None, str, str, str, str], Users] = {}
    db_not_teachers: dict[tuple[str | None, str, str, str, str, bool], Users] = {}

    if total_not_teacher_new_users < 0:
        raise ValueError("total_not_teacher_new_users cannot be negative")

    if total_not_teacher_new_users != _sum_values(num_of_roles_not_teachers):
        raise ValueError(
            "total_not_teacher_new_users must be equal to sum of num_of_roles_not_teachers values"
        )

    if password_hash_func is None:

        def not_a_hash(text: str) -> str:
            return text

        password_hash_func = not_a_hash

    total_new_users = len(teachers) + total_not_teacher_new_users

    # generate full names
    not_teacher_full_names: list[tuple[str, str]] = _generate_full_names(
        total_not_teacher_new_users, seed, False
    )

    # generate phone numbers
    all_phone_numbers = _generate_unique_phone_numbers(n=total_new_users, phone_len=9)
    not_teacher_phones = all_phone_numbers[:total_not_teacher_new_users]
    teacher_phones = all_phone_numbers[total_not_teacher_new_users:]

    # generate not teacher emails
    not_teacher_mails: list[str] = []
    for fn in not_teacher_full_names:
        mail = _generate_email(fn[0], fn[1], not_teacher_email_domain)
        not_teacher_mails.append(mail)

    # generate teacher emails
    teacher_mails: list[str] = []
    for fn_dict in teachers:
        mail = _generate_email(
            fn_dict["first_name"], fn_dict["last_name"], teacher_email_domain
        )
        teacher_mails.append(mail)

    # generate not teacher passwords
    not_teacher_passwords: list[str] = []
    for fn in not_teacher_full_names:
        password = _generate_password(fn[0], fn[1])
        not_teacher_passwords.append(password)

    # generate teacher passwords
    teacher_passwords: list[str] = []
    for fn_dict in teachers:
        password = _generate_password(fn_dict["first_name"], fn_dict["last_name"])
        teacher_passwords.append(password)

    # adding to db
    print(
        "NOT TEACHERS ========================================================================="
    )
    not_teacher_roles = _expand_roles(num_of_roles_not_teachers)
    idx = 0

    for person, phone, mail, password in zip(
        not_teacher_full_names,
        not_teacher_phones,
        not_teacher_mails,
        not_teacher_passwords,
    ):
        degree = None
        name = person[0]
        surname = person[1]
        password_hash = password_hash_func(password)
        curr_role_str: str = not_teacher_roles[idx]
        idx += 1
        curr_role_obj: Roles = roles[curr_role_str]
        print(
            f"{degree} {name} {surname} - {phone} - {mail} - {password} ({password_hash})"
        )

        user_key: tuple[str | None, str, str, str, str, bool] = (
            degree,
            name,
            surname,
            mail,
            password,
            curr_role_obj.role_name.lower() == "student",
        )
        user_obj = Users(
            password_hash=password_hash,
            email=mail,
            phone_number=phone,
            name=name,
            surname=surname,
            degree=degree,
            roles=[curr_role_obj],
            email_verified=True,
        )
        session.add(user_obj)
        db_not_teachers[user_key] = user_obj
        # db_not_teachers.append({user_key: user_obj})

    print()
    print()
    print(
        "TEACHERS ========================================================================="
    )
    instructor_role_obj: Roles = roles["Instructor"]
    for person_dict, phone, mail, password in zip(
        teachers, teacher_phones, teacher_mails, teacher_passwords
    ):
        degree = person_dict["degree"]
        name = person_dict["first_name"]
        surname = person_dict["last_name"]
        password_hash = password_hash_func(password)
        print(
            f"{degree} {name} {surname} - {phone} - {mail} - {password} ({password_hash})"
        )

        user_key: tuple[str | None, str, str, str, str] = (
            degree,
            name,
            surname,
            mail,
            password,
        )
        user_obj = Users(
            password_hash=password_hash,
            email=mail,
            phone_number=phone,
            name=name,
            surname=surname,
            degree=degree,
            roles=[instructor_role_obj],
            email_verified=True,
        )
        session.add(user_obj)
        db_teachers[user_key] = user_obj

    session.flush()
    return db_teachers, db_not_teachers
