import hashlib
import random
from typing import Callable

from sqlalchemy.orm import Session
from backend.src.users.models import Users, Roles


def _read_list_from_txt(sourcefile: str) -> list[str]:
    """
    Reads a text file into a list
    :param sourcefile: txt file with list of names/surnames, one per line
    :return: list of names/surnames with whitespace removed and capitalized
    """
    with open(sourcefile, "r", encoding="utf-8") as f:
        lines = f.readlines()
    lines = [line.strip().capitalize() for line in lines]
    return lines


def _generate_full_names(
    names: list[str], surnames: list[str], n: int, with_duplicates: bool = False
) -> list[tuple[str, str]]:
    """
    Generates a list of full names by randomly combining names and surnames.
    :param names: list of names
    :param surnames: list of surnames
    :param n: number of full names
    :return: list of full names
    """
    if with_duplicates:
        return [(random.choice(names), random.choice(surnames)) for _ in range(n)]
    else:
        max_combinations = len(names) * len(surnames)
        if n > max_combinations:
            raise ValueError("Not enough unique combinations")

        result = set()

        while len(result) < n:
            pair = (random.choice(names), random.choice(surnames))
            result.add(pair)

        return list(result)


def _generate_email(name: str, surname: str, domain: str) -> str:
    """
    Generates an email address from name and surname
    :param name: name of email
    :param surname: surname of email
    :param domain: domain of email
    :return: email address
    """

    def _replace_polish_chars(text: str) -> str:
        mapping = {
            "ą": "a",
            "ć": "c",
            "ę": "e",
            "ł": "l",
            "ń": "n",
            "ó": "o",
            "ś": "s",
            "ż": "z",
            "ź": "z",
        }
        return "".join(mapping.get(c, c) for c in text)

    def _normalize(text: str) -> str:
        text = text.strip().lower()
        return _replace_polish_chars(text)

    name = name[:3]

    name = _normalize(name)
    surname = _normalize(surname)
    domain = _normalize(domain)

    return f"{name}.{surname}@{domain}"


def _generate_unique_phone_numbers(n: int, phone_len: int = 9) -> list[str]:
    """
    Generates a list of unique phone numbers
    :param n: number of phone numbers
    :param phone_len: phone number length
    :return: list of unique phone numbers
    """
    max_combinations = 10**phone_len

    if n > max_combinations:
        raise ValueError("Not enough unique combinations")

    numbers = set()
    while len(numbers) < n:
        num = random.randint(0, 999_999_999)
        formatted = f"{num:09d}"
        numbers.add(formatted)

    return list(numbers)


def _generate_password(name: str, surname: str) -> str:
    """
    Generates a simple password from name and surname
    :param name: name of user
    :param surname: surname of user
    :return: simple password
    """
    name = name.strip().lower()
    surname = surname.strip().lower()
    return f"{name}{surname}"


def change_me_hash(text: str) -> str:
    """
    Hash function ONLY FOR TESTS
    :param text: text to be hashed
    :return: hash
    """
    return hashlib.sha256(text.encode()).hexdigest()


def _sum_values(d: dict[str, int]) -> int:
    """
    Calculate sum of dictionary values
    :param d: dictionary
    :return: sum of dictionary values
    """
    sum: int = 0
    for k in d.keys():
        sum += d[k]
    return sum


def _expand_roles(num_of_roles: dict[str, int]) -> list[str]:
    """
    Creates a list of roles based on a dictionary where keys are role
        names and values are the number of users with that role.
    :param num_of_roles: dictionary where keys are role names and values
        are number of users with that role.
    :return: list of roles
    """
    return [role for role, count in num_of_roles.items() for _ in range(count)]


def generate_users(
    session: Session,
    roles: dict[str, Roles],
    num_of_roles_not_teachers: dict[str, int],
    teachers: list[dict[str, str]],
    n_males: int,
    n_females: int,
    password_hash_func: Callable[[str], str] | None,
    not_teacher_email_domain: str,
    teacher_email_domain: str,
    male_names_sourcefile: str,
    female_names_sourcefile: str,
    male_surnames_sourcefile: str,
    female_surnames_sourcefile: str,
) -> tuple[
    list[dict[tuple[str | None, str, str], Users]],
    list[dict[tuple[str | None, str, str], Users]],
]:
    # todo update doc
    """
    Generates a list of users (teachers and others)
    :param session: database session
    :param roles: dictionary mapping role names to Roles objects
        (generated by generate_roles_from_excel_file)
    :param num_of_roles_not_teachers: dictionary where keys are
        role names and values are number of users with that role.
    :param teachers: list of teachers generated by extract_teachers function
    :param n_males: number of not teacher males
    :param n_females: number of not teacher females
    :param password_hash_func: hash function for passwords
        (in case of None, hash is the same as plain password)
    :param not_teacher_email_domain: domain for not teacher email
    :param teacher_email_domain: domain for teacher email
    :param male_names_sourcefile: txt file with list of male names, one per line
    :param female_names_sourcefile: txt file with list of female names, one per line
    :param male_surnames_sourcefile: txt file with list of male surnames, one per line
    :param female_surnames_sourcefile: txt file with list of female surnames, one per line
    :return: A tuple containing two lists of dictionaries.
        Each dictionary maps a key, represented as a tuple of
        (degree, name, surname), to a Users object.
        First dictionary contains teachers.
        Second dictionary contains non-teachers.
    """

    # list[dict[tuple[degree, name, surname], Users]]
    db_teachers: list[dict[tuple[str | None, str, str], Users]] = []
    db_not_teachers: list[dict[tuple[str | None, str, str], Users]] = []

    if n_males < 0 or n_females < 0:
        raise ValueError("n_males and n_females cannot be negative")

    if n_males + n_females != _sum_values(num_of_roles_not_teachers):
        raise ValueError(
            "n_males and n_females must be equal to sum of num_of_roles_not_teachers values"
        )

    if password_hash_func is None:

        def not_a_hash(text: str) -> str:
            return text

        password_hash_func = not_a_hash

    # read from files
    male_names = _read_list_from_txt(sourcefile=male_names_sourcefile)
    female_names = _read_list_from_txt(sourcefile=female_names_sourcefile)
    male_surnames = _read_list_from_txt(sourcefile=male_surnames_sourcefile)
    female_surnames = _read_list_from_txt(sourcefile=female_surnames_sourcefile)

    total_not_teacher_new_users = n_males + n_females
    total_new_users = len(teachers) + total_not_teacher_new_users

    # generate full names (not teachers)
    male_full_names = _generate_full_names(
        male_names, male_surnames, n=n_males, with_duplicates=False
    )

    female_full_names = _generate_full_names(
        female_names, female_surnames, n=n_females, with_duplicates=False
    )

    not_teacher_full_names: list[tuple[str, str]] = male_full_names + female_full_names

    # generate phone numbers
    all_phone_numbers = _generate_unique_phone_numbers(n=total_new_users, phone_len=9)
    not_teacher_phones = all_phone_numbers[:total_not_teacher_new_users]
    teacher_phones = all_phone_numbers[total_not_teacher_new_users:]

    # generate not teacher emails
    not_teacher_mails: list[str] = []
    for fn in not_teacher_full_names:
        mail = _generate_email(fn[0], fn[1], not_teacher_email_domain)
        not_teacher_mails.append(mail)

    # generate teacher emails
    teacher_mails: list[str] = []
    for fn_dict in teachers:
        mail = _generate_email(
            fn_dict["first_name"], fn_dict["last_name"], teacher_email_domain
        )
        teacher_mails.append(mail)

    # generate not teacher passwords
    not_teacher_passwords: list[str] = []
    for fn in not_teacher_full_names:
        password = _generate_password(fn[0], fn[1])
        not_teacher_passwords.append(password)

    # generate teacher passwords
    teacher_passwords: list[str] = []
    for fn_dict in teachers:
        password = _generate_password(fn_dict["first_name"], fn_dict["last_name"])
        teacher_passwords.append(password)

    # adding to db
    print(
        "NOT TEACHERS ========================================================================="
    )
    not_teacher_roles = _expand_roles(num_of_roles_not_teachers)
    idx = 0

    for person, phone, mail, password in zip(
        not_teacher_full_names,
        not_teacher_phones,
        not_teacher_mails,
        not_teacher_passwords,
    ):
        degree = None
        name = person[0]
        surname = person[1]
        password_hash = password_hash_func(password)
        curr_role_str: str = not_teacher_roles[idx]
        idx += 1
        curr_role_obj: Roles = roles[curr_role_str]
        print(
            f"{name} {surname} - {phone} - {mail} - {password} ({password_hash}) - {degree}"
        )

        user_key: tuple[str | None, str, str] = (degree, name, surname)
        user_obj = Users(
            password_hash=password_hash,
            email=mail,
            phone_number=phone,
            name=name,
            surname=surname,
            degree=degree,
            roles=[curr_role_obj],
        )
        session.add(user_obj)
        db_not_teachers.append({user_key: user_obj})

    print()
    print()
    print(
        "TEACHERS ========================================================================="
    )
    instructor_role_obj: Roles = roles["Instructor"]
    for person_dict, phone, mail, password in zip(
        teachers, teacher_phones, teacher_mails, teacher_passwords
    ):
        degree = person_dict["degree"]
        name = person_dict["first_name"]
        surname = person_dict["last_name"]
        password_hash = password_hash_func(password)
        print(
            f"{degree} {name} {surname} - {phone} - {mail} - {password} ({password_hash})"
        )

        user_key: tuple[str | None, str, str] = (degree, name, surname)
        user_obj = Users(
            password_hash=password_hash,
            email=mail,
            phone_number=phone,
            name=name,
            surname=surname,
            degree=degree,
            roles=[instructor_role_obj],
        )
        session.add(user_obj)
        db_teachers.append({user_key: user_obj})

    session.flush()
    return db_teachers, db_not_teachers

    #
    # if "__main__" == __name__:
    #     # from extract_teachers func
    #     sample_teachers = [
    #         {"first_name": "Sławomir", "last_name": "Ścieszko", "degree": "mgr"},
    #         {
    #             "first_name": "Krzysztof",
    #             "last_name": "Ślot",
    #             "degree": "prof. dr hab. inż.",
    #         },
    #         {"first_name": "Agnieszka", "last_name": "Świderek", "degree": "mgr"},
    #         {"first_name": "Bożena", "last_name": "Świątek", "degree": "dr"},
    #         {"first_name": "Paweł", "last_name": "Żak", "degree": "dr inż."},
    #     ]

    # # one role per user
    # num_of_roles_not_teachers = {
    #     "Administrator": 0,
    #     "Schedule Manager": 0,
    #     "Dean's Office": 0,
    #     "Head of Unit": 0,
    #     "Instructor": 0,
    #     "Student": 20,
    #     "Administrative Staff": 0,
    #     "Guest": 0,
    # }

#     db_teachers, db_not_teachers = generate_users(
#         # session=...,
#         teachers=sample_teachers,
#         n_males=10,
#         n_females=10,
#         password_hash_func=change_me_hash,
#         not_teacher_email_domain="edu.p.lodz.pl",
#         teacher_email_domain="p.lodz.pl",
#         male_names_sourcefile=r"../data/male_names.txt",
#         female_names_sourcefile=r"../data/female_names.txt",
#         male_surnames_sourcefile=r"../data/male_surnames.txt",
#         female_surnames_sourcefile=r"../data/female_surnames.txt"
#     )
